### ISSUE TITLE
Incorrect psi values from DCD trajectory that has been rms aligned by cpptraj

### ISSUE THREAD

**Issue by diogomart** [MDAnalysis/mdanalysis#4505] opened 2024-03-13 01:51 UTC
MDAnalysis is calculating incorrect backbone dihedral psi values. In a trajectory with 1000 frames, got 4 incorrect values, so less than 1% of the values are incorrect. but the errors are in the order of tens of degrees.

MDAnalysis 2.7.0, Python 3.11, Ubuntu.

Here is code to reproduce the behavior, and associated data: [mdanalysis-psi-bug.zip](https://github.com/MDAnalysis/mdanalysis/files/14580797/mdanalysis-psi-bug.zip)
```python
from MDAnalysis import Universe
from MDAnalysis.analysis import dihedrals
import matplotlib.pyplot as plt

u = Universe("system.prmtop", ["traj.dcd"])

psis = [res.psi_selection() for res in u.residues[1:9]]
dihs = dihedrals.Dihedral(psis).run()

with open("cpptraj-psi_tyr5.txt") as f:
    f.readline()
    cpptrajvalues = []
    for line in f:
        cpptrajvalues.append(float(line.split()[1]))

mdavalues = dihs.angles[:, 3]  # psi angle of Tyr 5

# print a few values around frame 110 (1-based) to make sure dihedrals match those in visual inspection
for i in range(9):
    j = 105 + i
    print(f"frame {j=} {j+1=} {cpptrajvalues[j]=:.3f} {mdavalues[j]=:.3f}")

plt.gcf().set_size_inches(4, 2.4)
plt.plot(cpptrajvalues - mdavalues, ".")
plt.xlabel("frame")
plt.ylabel("difference in psi angle")
plt.title("cpptraj - MDAnalysis")
plt.subplots_adjust(left=0.2, bottom=0.2)
plt.savefig("plot.png", dpi=300)

```

The code prints a few values before and after frame 110 (1-based), which is the first frame for which a psi angle is incorrect. Visual inspection with pymol shows that the value from cpptraj is correct.
```
frame j=105 j+1=106 cpptrajvalues[j]=124.231 mdavalues[j]=124.232
frame j=106 j+1=107 cpptrajvalues[j]=127.769 mdavalues[j]=127.769
frame j=107 j+1=108 cpptrajvalues[j]=115.657 mdavalues[j]=115.657
frame j=108 j+1=109 cpptrajvalues[j]=124.622 mdavalues[j]=124.622
frame j=109 j+1=110 cpptrajvalues[j]=140.375 mdavalues[j]=-179.806
frame j=110 j+1=111 cpptrajvalues[j]=129.138 mdavalues[j]=129.139
frame j=111 j+1=112 cpptrajvalues[j]=128.170 mdavalues[j]=128.169
frame j=112 j+1=113 cpptrajvalues[j]=125.059 mdavalues[j]=125.059
frame j=113 j+1=114 cpptrajvalues[j]=126.200 mdavalues[j]=126.200
```

Plot of the difference between psi angles calculated with cpptraj and MDAnalysis:

![plot](https://github.com/MDAnalysis/mdanalysis/assets/1564797/93ffd65f-a2a2-49a6-b5ff-464ad72ba5dd)

**Comment by hmacdope** [comment] 2024-03-15 00:42
My best guess is that this is to do with the trajectory wrapping and how this is handled between the two codes. Do you know if your PSI angle is broken over the PBC (especially at those critical frames). Try adding in a nojump transform as well: https://docs.mdanalysis.org/stable/documentation_pages/transformations/nojump.html

**Comment by hmacdope** [comment] 2024-03-25 10:52
Did a nojump transform solve your issue @diogomart ?

**Comment by diogomart** [comment] 2024-03-26 00:29
No, it raised an error:
```
MDAnalysis.exceptions.NoDataError: Periodic box dimensions are not invertible at step 48
```
The trajectory had already been imaged by cpptraj, and loading it in Pymol shows no jumps. However cpptraj also prints this warning:
```
unit cell is not symmetric. Box cannot be properly stored as Charmm DCD
```
according to http://archive.ambermd.org/202108/0060.html this warning is because I aligned the trajectory to a reference, so the box is now rotating with respect to cartesian axes

**Comment by diogomart** [comment] 2024-03-28 01:55
If I remove the box information as in the code below, the values from MDAnalysis agree with those from cpptraj and pymol
```python
dim = np.array([0, 0, 0, 0, 0, 0])
transform = transformations.boxdimensions.set_dimensions(dim)
u.trajectory.add_transformations(transform)
```

**Comment by orbeckst** [comment] 2024-03-29 19:10
Thanks for testing removing the box.

Can you please run your analysis on the _raw_ trajectory, i.e., the one that was _not_ processed by cpptraj and in particular which does not contain any rotation/fitting? Does this give the right answer (i.e. no spikes/disagreement with cpptraj)?

**Comment by diogomart** [comment] 2024-03-29 21:38
Did something similar: imaged the trajectory with cpptraj but didn't align the protein to a reference, to keep the box aligned the x-axis (cpptraj didn't warn about _"unit cell is not symmetric. Box cannot be properly stored as Charmm DCD"_). With this processed trajectory the angles from MDAnalysis agree with cpptraj.

I'll check with the unprocessed trajectory and report back.

**Comment by diogomart** [comment] 2024-03-30 17:18
MDAnalysis and cpptraj agree also with the unprocessed trajectory.

**Comment by orbeckst** [comment] 2024-03-30 18:16
Then I think the issue is that MDAnalysis will correct for PBC but this requires the correct box in the trajectory. The box is correct in the raw trajectory. But once you fit and rotate, this information is not correct anymore and the PBC correction can give incorrect values.

From MDAnalysis's perspective, nothing goes wrong because it's the user's responsibility to provide consistent data. However, it would be good to have some warnings or at least document the behavior.

I don't remember if there's a way to disable PBC correction with keyword arguments. Otherwise, your workaround with setting the box to zero is valid.

**Comment by diogomart** [comment] 2024-03-30 18:33
Makes sense. Thank you for looking into it.

**Comment by hmacdope** [comment] 2024-04-01 10:08
I am going to close this @diogomart, feel free to re-open if you have any further questions.

**Closed as completed by hmacdope** 2024-04-01 10:08 UTC
Labels: Component-Analysis, PBC
