### ISSUE TITLE
Generating rmsfit_adk_dims.dcd outside temporary directory

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2639] opened 2020-03-21 23:58 UTC
## Expected behavior ##

There is no `rmsfit_adk_dims.dcd` in `MDAnalysisTests/data/`.

## Actual behavior ##

Two recent unrelated PR's have this mysterious file:

* https://github.com/MDAnalysis/mdanalysis/pull/2614#pullrequestreview-377846128
* https://github.com/MDAnalysis/mdanalysis/pull/2638/files#diff-216eba108275dddf90ef894a79bb8699

## Code to reproduce the behavior ##

I can't reproduce this bug myself, but I assume it's related to this test:

https://github.com/MDAnalysis/mdanalysis/blob/9a0a6573caaa0b5471f35a1304c13d4450c5cd47/testsuite/MDAnalysisTests/analysis/test_align.py#L210-L217

~I am probably missing something super obvious, but I'm not sure where `tempdir` is imported from. In `test_align.py` it's imported from `MDAnalysisTests`, but `MDAnalysisTests.__init__.py` doesn't import `tempdir`.~

https://github.com/MDAnalysis/mdanalysis/blob/9a0a6573caaa0b5471f35a1304c13d4450c5cd47/testsuite/MDAnalysisTests/analysis/test_align.py#L32

Edit: `tempdir` is `tempdir.py`, which defines a class for temporary directories.

~Regardless, tests could just use the [tmpdir fixture of pytest](https://docs.pytest.org/en/latest/tmpdir.html#the-tmpdir-fixture) and write files with `with tmpdir.as_cwd()`.~

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 0.20.2-dev
- Which version of Python (`python -V`)? 3.7.3
- Which operating system? MacOS Mojave

**Comment by siddharthjain1611** [comment] 2020-03-22 03:35
Actually there was a `rmsfit_adk_dims.dcd` file in a my local repository but I didn't push it.

**Comment by IAlibay** [comment] 2020-03-22 12:17
Strange, I can't reproduce this on my end either (Ubuntu 18.04 TLS, py3.7).

**Comment by lilyminium** [comment] 2020-03-22 12:33
Yes, I'm not so sure it's a bug, but it is strange that this exact file has popped up twice, and in the `data/` directory, as IIRC the default behaviour of `AlignTraj` is to write to the current directory. Maybe it's a Python version / OS version pairing?

@siddharthjain1611 and @Oscuro-Phoenix, would you mind letting us know which version of Python you're running and on which operating system?

**Comment by Oscuro-Phoenix** [comment] 2020-03-22 12:58
Well, I'm using Python 3.7.3 on Ubuntu 18.04 LTS

**Comment by IAlibay** [comment] 2020-03-22 13:20
@Oscuro-Phoenix starting from a branch that is even with MDAnalysis' `develop`, can you confirm that running pytest on `test_align.py` generates that file?

**Comment by Oscuro-Phoenix** [comment] 2020-03-22 13:26
Sure, i'm on that.

**Comment by Oscuro-Phoenix** [comment] 2020-03-22 13:34
Yes, it generates "rmsfit_adk_dims.dcd".

**Comment by orbeckst** [comment] 2020-03-23 06:55
@shfrz – could you please explain your 👎  comment on @Oscuro-Phoenix perfectly reasonable and friendly comment https://github.com/MDAnalysis/mdanalysis/issues/2639#issuecomment-602200553 ? Especially for new community members it can come across as unwelcoming if their comments are marked in this way without any explanation. Our [Code of Conduct](https://www.mdanalysis.org/pages/conduct/) explicitly states that we want to be a **welcoming** and **respectful** community and that **when we disagree, try to understand why**  — the latter can mean that when you disagree with an opinion to take the extra 2 minutes to explain yourself instead of simply leaving what can be interpreted as a discouraging "downvote". 

Furthermore, **as scientists** we are perfectly happy to engage in discussions and it's totally fine (and expected) to have different points of view. The goal is to eventually arrive at a common view or solution, but importantly, we discuss the specific issues using rational arguments and evidence. "Upvotes" 👍 and "Downvotes" 👎 are _not_ a scientific discussion. As thus, we really only use them in two ways: (1) When we have an actual vote (e.g., on proposals for features) and in these cases this will be obvious. (2) As a quick sign of encouragement or "Ok, I understand" – which obviously means that we rarely use 👎 .

You haven't been part of the MDAnalysis community for very long, @shfrz, so it's normal that you haven't learned all the explicit and implicit rules. MDAnalysis is a a growing community, which is great, and we are very happy that you and many others are becoming part of it. Like any growing community, we are bound to have overlooked things or not have made expectations as clear as we should. But we believe that it's best for a healthy community when standards and expectations are made clear publicly and immediately so we hope that this comment helps everyone to make MDAnalysis a community where you are happy to contribute and thrive.

— @orbeckst  (for @MDAnalysis/coredevs )

**Comment by orbeckst** [comment] 2020-03-23 07:04
Apologies in advance, I haven't had the time to look into this in detail, so just some (potentially irrelevant) remarks:
- `rmsfit_adk_dims.dcd` – could this be generated by the PSA tests? 
- Why are we still using a local `tempdir.py` — we should be using `pytest`'s fixture instead.

**Comment by siddharthjain1611** [comment] 2020-03-23 07:47
> Yes, I'm not so sure it's a bug, but it is strange that this exact file has popped up twice, and in the `data/` directory, as IIRC the default behaviour of `AlignTraj` is to write to the current directory. Maybe it's a Python version / OS version pairing?
> 
> @siddharthjain1611 and @Oscuro-Phoenix, would you mind letting us know which version of Python you're running and on which operating system?

So Sorry for the late reply ma'am , I am using Python version 3.7

**Comment by shfrz** [comment] 2020-03-23 09:02
First of all my sincere apologies for the downvote. It was a indeed a
mistake.

@orkbest, the downvote happened unknowingly, there was a little instability
with my cursor and mouse. I didn't even see that comment.

Yes, I totally agree this is a great and healthy community. I haven't been
around here so long but I have surely learned a lot here.

I assure you that I will be more careful next time.

A very big thank you for bringing it to my notice.

**Comment by Oscuro-Phoenix** [comment] 2020-03-23 09:38
Hey, guys. Its fine, I am sufficiently into this to stay motivated. And, I request all the members to feel free to down-vote anything that deserves it. It will push me to try and ameliorate. 

@shfrz Its totally fine. 

@orbeckst  Thanks a lot.

**Comment by lilyminium** [comment] 2020-03-23 09:45
All good @shfrz, thanks for clarifying.

> Yes, it generates "rmsfit_adk_dims.dcd".

Thanks @Oscuro-Phoenix for that. @siddharthjain1611, if you delete the `rmsfit_adk_dims.dcd` file in `testsuite/MDAnalysisTests/data/` now, and re-run `pytest test_align.py`, does the file get regenerated? Are you also on Ubuntu?

> could this be generated by the PSA tests?

I did wonder if something else might be generating it @orbeckst. The criteria for `AlignTraj` writing a file out to `rmsfit_{original_filename}` is:
* trajectory is not in memory
* AlignTraj does not specify `in_memory=True`
* `filename` is not specified in `AlignTraj`. 

PSA does use `AlignTraj`, but appends '_fit' to the end of the filename by default. The tests in `test_pca` and `test_encore` all operate on trajectories in memory. Basically all the other tests in `test_align` specify a `filename` along the lines of 'align_test.dcd'. So I think it has to be that one test, or something else in the code entirely -- but I have no idea why this would be coming up for @Oscuro-Phoenix and @siddharthjain1611 only, especially when @Oscuro-Phoenix has the same setup as @IAlibay.

**Comment by siddharthjain1611** [comment] 2020-03-23 12:58
> All good @shfrz, thanks for clarifying.
> 
> > Yes, it generates "rmsfit_adk_dims.dcd".
> 
> Thanks @Oscuro-Phoenix for that. @siddharthjain1611, if you delete the `rmsfit_adk_dims.dcd` file in `testsuite/MDAnalysisTests/data/` now, and re-run `pytest analysis/test_align.py` from `MDAnalysisTests`, does the file get regenerated? Are you also on Ubuntu?
> 
> > could this be generated by the PSA tests?
> 
> I did wonder if something else might be generating it @orbeckst. The criteria for `AlignTraj` writing a file out to `rmsfit_{original_filename}` is:
> 
> * trajectory is not in memory
> * AlignTraj does not specify `in_memory=True`
> * `filename` is not specified in `AlignTraj`.
> 
> PSA does use `AlignTraj`, but appends '_fit' to the end of the filename by default. The tests in `test_pca` and `test_encore` all operate on trajectories in memory. Basically all the other tests in `test_align` specify a `filename` along the lines of 'align_test.dcd'. So I think it has to be that one test, or something else in the code entirely -- but I have no idea why this would be coming up for @Oscuro-Phoenix and @siddharthjain1611 only, especially when @Oscuro-Phoenix has the same setup as @IAlibay.
> 
> Edit: the fact that `AlignTraj.run()` is not called in the test doesn't matter, as the file writer is created and opened in `AlignTraj.__init__`. It should probably not do that.

Sir, I'm using Mac OS Catalina 10.15.3

**Comment by siddharthjain1611** [comment] 2020-03-23 12:59
No, ma'am, the file doesn't appear again.

**Comment by lilyminium** [comment] 2020-03-28 12:04
Thanks @siddharthjain1611, although it did pop up again in #2614, so this doesn't seem to be a one-off thing. Maybe we can change `AlignTraj` to open the file writer in `_prepare` instead of `__init__` and see if that helps?

**Comment by IAlibay** [comment] 2022-01-19 01:31
As far as I'm aware we were never able to replicate this issue. Given that tempdir has now been removed in #2682, it's unclear that we'll be able to replica this. Do we want to close the issue and re-raise if it happens again?

**Comment by jbarnoud** [comment] 2022-02-10 09:58
I cannot reproduce the error with the current state of the develop branch (3c0875c7b25bf97a5a2d70f8c31bd661072911ec). Closing for now. Please, feel free to reopen this issue if it comes up again.

**Closed by jbarnoud** 2022-02-10 09:58 UTC
Labels: close?
