### ISSUE TITLE
Secondary structure determination

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/mdanalysis#2608] opened 2020-03-10 06:17 UTC
## Is your feature request related to a problem? ##
`gmx do_dssp` isn't making nice with DSSP version 3.1.4, and I would like to quantify the secondary structure of my protein.

## Describe the solution you'd like ##
An MDAnalysis version where I don't need to load my entire trajectory into memory.

## Describe alternatives you've considered ##
MDTraj has `compute_dssp` but it loads the trajectory into memory.

**Comment by orbeckst** [comment] 2023-10-10 02:35
Duplicate of  #1612 (but admittedly, this issue is more concise) so I am copying it to the older one and then close this one.

**Closed by orbeckst** 2023-10-10 02:35 UTC
Labels: Component-Analysis
