### ISSUE TITLE
Release 0.15.0

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#752] opened 2016-03-01 23:57 UTC
Discussions for release 0.15.0

~~Note that with [semantic versioning](/MDAnalysis/mdanalysis/wiki/SemanticVersioning) no new features can be in this release. If we want new features, we will have to make it 0.15.0.~~ -- Contact Analysis happened, so this is now a full release.

(edited by Richard)

**Comment by kain88-de** [comment] 2016-03-02 08:48
How should the branches then be handled? Due to me merging the new contact analysis develop is now targeting 0.15.0. We can cherry-pick from develop to master and publish from master directly once we solved the important bugs for 0.14.0. For the 0.15.0 release @richardjgowers would then have to merge develop into master instead of just rebasing (this might lead to some commits appearing twice in the history).

Sorry for creating the mess by merging the contact analysis branch so eagerly

**Comment by richardjgowers** [comment] 2016-03-02 09:46
I don't see the point in a 14.1 it's just going to cause headaches. We'll
call the next one 15 (contact and deprecations) and topology becomes 16

**Comment by orbeckst** [comment] 2016-03-02 16:06
On 2 Mar, 2016, at 02:46, Richard Gowers wrote:

> I don't see the point in a 14.1 it's just going to cause headaches. We'll
> call the next one 15 (contact and deprecations) and topology becomes 16

Yes, that works, too.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by kain88-de** [comment] 2016-03-18 10:23
@richardjgowers should we set the release target to a more realistic end of april instead of 8 days ago?

**Comment by orbeckst** [comment] 2016-03-21 05:43
I set it to [April 1](https://en.wikipedia.org/wiki/April_Fools'_Day) but @richardjgowers should change it... I just didn't want to see the red "milestone delayed" messages anymore, especially while we're in the GSoC applicant vetting period.

I also edited the description, it's going to be more than just bug fixes.

It's most important function is to getting us closer to the semi-mythical day when **363** will finally be merged... no pressure @richardjgowers and @dotsdl ... ;-)

**Comment by kain88-de** [comment] 2016-03-21 15:41
I was thinking how to motivate @richardjgowers and @dotsdl. What was left to do to merge the branch?

**Comment by jbarnoud** [comment] 2016-03-21 15:45
@kain88-de tests among other things. Last time I had a look, a bunch of tests where failing in the 363 branch.

A procedure to pinpoint regressions would be useful too as `develop` evolved quite a bit since `issue-363` started.

**Comment by richardjgowers** [comment] 2016-03-21 15:48
Haha I'm finishing up my thesis, so not unmotivated but maybe a little preoccupied!

The hold up to this release is we wanted deprecations of things that will change once 363 gets merged, for example `SegmentGroup.positions` doesn't give you per-atom behaviour.  So anything that isn't an AtomGroup doing AtomGroup things needs a warning.

**Comment by richardjgowers** [comment] 2016-03-21 15:52
And then to get the PR done, yeah lots of tests.  The old AtomGroup tests are a little haphazard and rely on `_atoms` among things, so they need rewriting.

**Comment by dotsdl** [comment] 2016-03-21 16:21
Hey all, just like @richardjgowers, I'm not unmotivated but preoccupied. Been on a tear to release [`datreant.core`](https://github.com/datreant/datreant.core), and hopefully doing that by the end of today. I'll be returning to and finishing #698 by the end of the week so we can move this release along.

**Comment by orbeckst** [comment] 2016-03-23 21:03
FYI: There are a bunch of methods in the code that are scheduled for removal in 0.15.0, for instance `AtomGrouyp.selectAtoms()`.

**Comment by kain88-de** [comment] 2016-04-18 07:39
OK I think we are almost done with this release. There is very little left to do. The release won't contain much and we can aim for a very big release 0.16.0 at the end of the summer.

TODO
---------

- [ ] fix warnings introduced in #698, check #828, #825 
- [ ] fix up new new contacts class see #792

**Comment by kain88-de** [comment] 2016-05-03 20:35
@MDAnalysis/coredevs what is still needed to make this happen before the end of the month?

**Comment by mnmelo** [comment] 2016-05-04 14:27
I'm still busy with #799, which turns out to be a deep rabbit hole for several reasons. I'm fine with leaving that for 16.0, but am currently devoting more time to it so I can get rid of it asap.

**Comment by richardjgowers** [comment] 2016-05-04 19:50
Ok so 0.15 release this weekend!

**Comment by orbeckst** [comment] 2016-05-04 20:55
Did we remove deprecated names such as `selectAtoms()` https://github.com/MDAnalysis/mdanalysis/issues/752#issuecomment-200542507 ?

**Comment by kain88-de** [comment] 2016-05-05 08:19
@mnmelo We can just add a warning about the missing cython package for development installations in the next release. Then you have some time for a proper fix.

@orbeckst Nope not yet.

**Comment by kain88-de** [comment] 2016-05-05 08:21
@orbeckst These deprecations have been moved by @dotsdl to 0.16.0

**Comment by kain88-de** [comment] 2016-05-06 17:22
@richardjgowers can we also make a minor release for GridDataFormats? I changed some stuff there to and I think it be nicer to have a non-dev version on conda.

**Comment by orbeckst** [comment] 2016-05-06 17:23
> On 6 May, 2016, at 10:22, kain88-de <notifications@github.com> wrote:
> 
> @richardjgowers can we also make a minor release for GridDataFormats? I changed some stuff there to and I think it be nicer to have a non-dev version on condo.

@kain88-de – you can make a GridDataFormat release yourself, you should have all the authority that you need (if not, tell me what’s missing). Just update the MDA setup.py accordingly.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by kain88-de** [comment] 2016-05-06 18:41
I'm not aware I have rights to push to pypi too. I can make everything on github and conda that's about it.

**Comment by orbeckst** [comment] 2016-05-06 19:16
I will add you. What’s your username on PyPi?

> On 6 May, 2016, at 11:41, kain88-de <notifications@github.com> wrote:
> 
> I'm not aware I have rights to push to pypi too. I can make everything on github and conda that's about it. 
> 
> 

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by kain88-de** [comment] 2016-05-06 20:12
@orbeckst thanks that's a nice offer. But I have enough responsibilities as it is and don't want to have rights for PyPi right now.

**Comment by orbeckst** [comment] 2016-05-06 20:32
> On 6 May, 2016, at 13:12, kain88-de <notifications@github.com> wrote:
> 
> @orbeckst thanks that's a nice offer. But I have enough responsibilities as it is and don’t want to have rights for PyPi right now.

Then you have to tell me when to do a new release – apparently, in the past I was the one who did it because there’s no other maintainer on PyPi.

(I am more than happy to also hand this to @richardjgowers if he wants to, of course ;-))

Anyway, open an issue for a new GridDataFormats release and we can quickly push it out.

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Comment by richardjgowers** [comment] 2016-05-09 10:51
So we're getting some (intermittent) failures on the Mac OS 2.7 minimal job.  It looks like it's failing to create new file handles, which last time was caused by Universes not closing properly (and so each test creating a new handle, eventually hitting the upper limit on these).  Looking into this.

**Comment by kain88-de** [comment] 2016-05-10 20:13
The builds pass again. What did you change?

**Comment by richardjgowers** [comment] 2016-05-10 20:15
Literally nothing :S

**Comment by jbarnoud** [comment] 2016-05-10 20:17
On 10/05/16 22:15, Richard Gowers wrote:
>
> Literally nothing :S
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/MDAnalysis/mdanalysis/issues/752#issuecomment-218277424>
>
I restarted a build on travis earlier today. The failing badge was 
bothering me. Now I realize I made it more difficult to investigate, sorry.

**Comment by richardjgowers** [comment] 2016-05-11 15:29
So on the full Linux build, we got this:
```
======================================================================

ERROR: test_density_from_Universe (MDAnalysisTests.analysis.test_density.Test_density_from_Universe)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/numpy/testing/decorators.py", line 147, in skipper_func

    return f(*args, **kwargs)

  File "/home/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysisTests/analysis/test_density.py", line 102, in setUp

    self.universe = mda.Universe(self.topology, self.trajectory)

  File "/home/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysis/core/AtomGroup.py", line 4353, in __init__

    self.load_new(coordinatefile, **kwargs)

  File "/home/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysis/core/AtomGroup.py", line 4889, in load_new

    self.trajectory = reader(filename, **kwargs)    # unified trajectory API

  File "/home/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysis/coordinates/XDR.py", line 80, in __init__

    self._load_offsets()

  File "/home/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysis/coordinates/XDR.py", line 114, in _load_offsets

    data = read_numpy_offsets(fname)

  File "/home/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysis/coordinates/XDR.py", line 61, in read_numpy_offsets

    return {k: v for k, v in six.iteritems(np.load(filename))}

  File "/home/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 399, in load

    pickle_kwargs=pickle_kwargs)

  File "/home/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 162, in __init__

    _zip = zipfile_factory(fid)

  File "/home/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/numpy/lib/npyio.py", line 92, in zipfile_factory

    return zipfile.ZipFile(*args, **kwargs)

  File "/home/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/zipfile.py", line 770, in __init__

    self._RealGetContents()

  File "/home/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/zipfile.py", line 811, in _RealGetContents

    raise BadZipfile, "File is not a zip file"

BadZipfile: File is not a zip file
```

I'm going to assume it's just a travis hiccup and redo the build

**Comment by kain88-de** [comment] 2016-05-11 15:36
What the heck?  I ran the full testsuite in the morning on my laptop everything passed.

**Comment by kain88-de** [comment] 2016-05-12 07:47
@richardjgowers where do we stand on build? Just assume that travis has some random hickups lately?

**Comment by richardjgowers** [comment] 2016-05-12 07:51
Yeah all seems good now

**Comment by kain88-de** [comment] 2016-05-12 08:01
So a release this weekend?

**Comment by richardjgowers** [comment] 2016-05-12 09:00
Yeah I wanted to do it last weekend but we had failures everywhere.  Is the
conda build process documented enough for me to do it? Or did you want to
do it?

**Comment by kain88-de** [comment] 2016-05-12 09:24
@richardjgowers I can do it after you made the release. I will also add documentation for it on the wiki soon, it is a little bit more involved since you need to build it on a special virtual machine.

**Comment by richardjgowers** [comment] 2016-05-12 12:08
Ok we got the weird failure again [here](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/129681978). There's lots of errors, but it looks like it's because we can't open files, many because we've got too many open simultaneously? (`IOError: [Errno 24] Too many open files: '/Users/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysisTests/data/adk_dims.dcd'`)

We had this before which was caused by Universes not deleting properly, causing handles to remain open, but the extra checks in #323 should be reporting if this is happening?

The only other change I can think of is the tempdir, but this was just copy pasting the code into our repo right?

**Comment by richardjgowers** [comment] 2016-05-16 08:55
Ok, master branch updated, we're live on Pypi, docs uploaded to github and pypi docs.  @kain88-de sorry about the delay

**Comment by kain88-de** [comment] 2016-05-16 09:29
@richardjgowers thanks for publishing. Don't worry about the delay it's still weekend in Germany thanks to national holidays

**Closed** 2016-05-16 09:29 UTC
Labels: release

**Comment by kain88-de** [comment] 2016-05-16 11:17
https://anaconda.org/MDAnalysis/mdanalysis/files

conda release is online

**Comment by dotsdl** [comment] 2016-05-16 18:33
Sweet, thanks @richardjgowers and @kain88-de for doing the heavy lifting!
