### ISSUE TITLE
Inaccurate trajectory subscripting for mol2 file with multiple entries

### ISSUE THREAD

**Issue by ftclark3** [MDAnalysis/mdanalysis#4060] opened 2023-03-09 18:02 UTC
As expected, it appears that a mol2 file with multiple entries can be read in normally and those entries looped over like a trajectory. However, subscripting the trajectory object only returns one (I believe the last) frame in the trajectory, no matter which index is used. It's easy enough to just loop over frames instead but this issue could potentially go unnoticed if someone was just looking at a single entry, for example.

## Expected behavior ##

Comparison of nonidentical frames returned by subscripting `u.trajectory` evaluates to False

## Actual behavior ##

The frames are identical

## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import mol2_molecules
u = mda.Universe(mol2_molecules)
u.trajectory[0] is u.trajectory[1]
```
returns True

## Current version of MDAnalysis ##

- MDAnalysis version 2.4.2
- Python version 3.10.6
- Ubuntu 2022.04

**Comment by IAlibay** [comment] 2023-03-09 18:15
Please do double check this, but I _think_ this is just an issue with the way equality is handled and not the timestep being fed properly, because if I do:

```
import MDAnalysis as mda
from MDAnalysisTests.datafiles import mol2_molecules
import numpy as np

u = mda.Universe(mol2_molecule)
a = u.trajectory[0].positions.copy()
b = u.trajectory[1].positions.copy()
np.all(a == b)
>> False
```

Indeed, as far as I can see, the position arrays are definitely different when indexed, it's just that the truth of:
```
u.trajectory[0].positions == u.trajectory[1].positions
```
and
```
u.trajectory[0] == u.trajectory[1]
```
do return true

**Comment by IAlibay** [comment] 2023-03-09 18:28
I suspect this is just that as you evaluate the indexing you inherently change the previous object (i.e. the comparison is done without a hard copy), so you're just doing a comparison on self? @richardjgowers might be better able to explain the situation here.

**Comment by orbeckst** [comment] 2023-03-09 20:38
The same happens for any other readers, for the reason @IAlibay mentioned. For example,
```python
In [1]: import MDAnalysis as mda
   ...: from MDAnalysisTests import datafiles as data

In [2]: u = mda.Universe(data.TPR, data.XTC)

In [3]: u.trajectory[0] == u.trajectory[1]
Out[3]: True
```
because `u.trajectory[n]` returns the *same Timestep* object and only its content is changed.

To see that you get different coordinates, make a copy of the positions
```python
In [6]: (u.trajectory[0].positions.copy() == u.trajectory[1].positions.copy()).all()
Out[6]: False
```

This is not a bug but one of the — perhaps confusing — ways that the trajectory readers work. One way to think about MDAnalysis's handling of a trajectory is that it provides an instantaneous view on a specific frame and any data you want to keep for downstream processing (when the frame will have changed) needs to be manually copied.

I am closing the issue because it is not a bug. If you have a specific suggestion where our documentation https://userguide.mdanalysis.org/ or https://docs.mdanalysis.org/ should be clearer then please let us know and we can reopen as an issue for docs.

**Closed as not planned by orbeckst** 2023-03-09 20:38 UTC
