### ISSUE TITLE
Set b-factor for PDB file

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#1359] opened 2017-05-22 12:44 UTC
### Expected behaviour
I have a pdb file which I want to set b-factors to the atoms. 

### Actual behaviour
The b-factor field in the pdb file is not changed

### Code to reproduce the behaviour

``` python
from MDAnalysis import Universe
from six import StringIO

pdb = 'ATOM      1  N   MET S   1      85.260  60.210  43.770  1.00  0.00      SYST N'
u = Universe(StringIO(pdb), format='pdb')
u.atoms.bfactors = 0.5
u.atoms.write('test.pdb')
```
The content of test.pdb:

> HEADER    
> TITLE     MDANALYSIS FRAME 0: Created by PDBWriter
> CRYST1    0.000    0.000    0.000   0.00   0.00   0.00 P 1           1
> ATOM      1  N   MET S   1      85.260  60.210  43.770  1.00  0.00      SYST N
> END

### Currently version of MDAnalysis:
py35, mda0.16.1

**Comment by kain88-de** [comment] 2017-05-22 13:46
See #1092 . The problem is that the bfactors aren't in the original topology and this needs to be updated not the atomgroup you selected there.

We are working  on it. There should also be a PR from @richardjgowers that fixes this. Some comments on the UI/API would be nice.

**Comment by orbeckst** [comment] 2017-06-15 20:11
I am going to re-open this one, even though it is a duplicate of #1092 because 

1. it is a common use case and anyone being bitten by the new topology system should be able to find this as an *open* issue
2. it breaks the official MDAnalysis tutorial [Example: Saving dynamic per-atom properties in B-factor](http://www.mdanalysis.org/MDAnalysisTutorial/writing.html#example-saving-dynamic-per-atom-properties-in-b-factor) (which admittedly needs an overhaul...).
3. it used to to work... so it's a regression

**Comment by orbeckst** [comment] 2017-08-05 01:03
Note: at the moment you have to do [manually add the tempfactors topology attribute](https://groups.google.com/d/msg/mdnalysis-discussion/OCGazyO4H0E/ZoKa98M3AgAJ)
```python
u.add_TopologyAttr(MDAnalysis.core.topologyattrs.Tempfactors(np.zeros(len(u.atoms))))

u.atoms.tempfactors = 0.5
u.atoms.write("withbfacs.pdb")
```

**Comment by orbeckst** [comment] 2017-08-21 23:58
We might not do much more here than properly document it. Opinions?

**Comment by richardjgowers** [comment] 2017-08-22 13:01
@orbeckst I think it is possible to make this behaviour work, I (or someone else) just needs to get the hacking done under the hood.  Short term documenting it is definitely a good thing though.

**Comment by weiHelloWorld** [comment] 2017-09-29 21:45
@orbeckst Just curious why "b-factor" is renamed "tempfactor" in the new version?

**Comment by orbeckst** [comment] 2017-09-29 21:50
*tempFactor* is the offical name in the [ATOM](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM) record of the PDB format. We don't like camelCase so we use tempfactor. We also use the convention that "arrays" are plural words, hence *tempfactors*.

The new usage is incompatible with previous versions of MDAnalysis where you could do things like `atoms.set_bfactors`. But that was a specialized hack. The new system is universal and fully internally consistent so it was worth breaking the old behavior but of course we know that it is always a hassle for users – sorry!

**Comment by weiHelloWorld** [comment] 2017-09-29 21:59
I see, thank you!

**Comment by orbeckst** [comment] 2017-12-15 23:20
This should work now with #1092 and is also documented under [Universe.add_TopologyAttr](https://www.mdanalysis.org/mdanalysis/documentation_pages/core/universe.html#MDAnalysis.core.universe.Universe.add_TopologyAttr).

**Closed by orbeckst** 2017-12-15 23:20 UTC
Labels: Component-Core, Component-Docs, defect

**Comment by orbeckst** [comment] 2017-12-15 23:22
@weiHelloWorld – just fyi, we added `bfactors`  back... see the example that I linked above.

**Comment by weiHelloWorld** [comment] 2017-12-15 23:25
@orbeckst Thank you!
