### ISSUE TITLE
Fails to make a universe from 2Y2N.pdb

### ISSUE THREAD

**Issue by kaceyreidy** [MDAnalysis/mdanalysis#936] opened 2016-08-15 21:28 UTC
When a universe should be created, a KeyError is raised.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-505-4af8f1cb9d1b> in <module>()
----> 1 mda.Universe(path + '2Y2N.pdb')

/usr/local/lib/python2.7/dist-packages/MDAnalysis/core/AtomGroup.pyc in __init__(self, *args, **kwargs)
   4337         try:
   4338             with parser(self.filename, universe=self) as p:
-> 4339                 self._topology = p.parse()
   4340         except IOError as err:
   4341             raise IOError("Failed to load from the topology file {0}"

/usr/local/lib/python2.7/dist-packages/MDAnalysis/topology/PDBParser.pyc in parse(self)
     88         structure['atoms'] = atoms
     89 
---> 90         bonds = self._parsebonds(atoms)
     91         structure['bonds'] = bonds
     92 

/usr/local/lib/python2.7/dist-packages/MDAnalysis/topology/PDBParser.pyc in _parsebonds(self, atoms)
    181                 atom, atoms = _parse_conect(line.strip())
    182                 for a in atoms:
--> 183                     bond = tuple([mapping[atom], mapping[a]])
    184                     bonds.add(bond)
    185 

KeyError: 3635

``` python
import MDAnalysis as mda

u = mda.Universe('2Y2N.pdb')
```

**Comment by jdetle** [comment] 2016-08-15 21:38
Hi @kaceyreidy, I'd be happy to try help. Are you able to share the `2Y2N.pdb`file such that I can try to reproduce the error? Also, if you could please run `python -c "import MDAnalysis as mda; print(mda.__version__)"` and share that info and let us know what OS you are running that can't hurt either.

**Comment by dotsdl** [comment] 2016-08-15 21:42
@jdetle this is a file for a structure on the PDB, namely 2Y2N. You can download it from [here](http://files.rcsb.org/download/2Y2N.pdb).

**Comment by kaceyreidy** [comment] 2016-08-15 21:42
Ubuntu 14.04.

**Comment by orbeckst** [comment] 2016-08-15 22:12
@jdetle , see https://github.com/MDAnalysis/mdanalysis/issues/810#issuecomment-239944822 : 
```python
import urllib 
downloader = urllib.URLopener()

def fetch_pdb(pdb_id, download_url="http://files.rcsb.org/download"):
    filename = "{0}.pdb".format(pdb_id.lower())
    downloader.retrieve("/".join([download_url, filename]), filename)
    return filename

# get file
pdb = fetch_pdb("2y2n")

# load pdb
u = mda.Universe(pdb)
```

**Comment by jdetle** [comment] 2016-08-15 22:38
@dotsdl, @orbeckst, the issue seems to be caused by the TER statement on line 8045. The comments in the _parse_bonds function alludes to problems with multiframe PDBs and the CONECT statements being given at the end of the file. It looks like this is a case where the error isn't caught. Any help?

**Comment by richardjgowers** [comment] 2016-08-20 12:46
So looking into this, there's a CONECT record between atoms and the TER record.  As the TER record doesn't represent a real Atom, would a good fix for this be to ignore bonds to the TER location?

**Comment by orbeckst** [comment] 2016-08-20 18:49
I think so, yes. I don't really know why one would have these pseudo bonds but it won't matter for MDAnalysis if they are there. It *might* be an issue when writing PDB files but I am willing to wait for someone to raise an issue for the PDBWriter about this…

> On 20 Aug, 2016, at 05:46, Richard Gowers <notifications@github.com> wrote:
> 
> So looking into this, there's a CONECT record between atoms and the TER record. As the TER record doesn't represent a real Atom, would a good fix for this be to ignore bonds to the TER location?

--
Oliver Beckstein * orbeckst@gmx.net
skype: orbeckst  * orbeckst@gmail.com

**Closed** 2016-08-24 14:02 UTC
Labels: Component-Readers, Format-PDB
