### ISSUE TITLE
check and update docs for 0.11.0

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/mdanalysis#382] opened 2015-08-05 19:04 UTC
As a corollary to #381 , we need to check **all** docs  (primarily the online docs, but also the wiki pages) for usage that changes between 0.10.0 and 0.11.0.

In particular, the owner of this issue should act as a task master and not shy away from delegating fixes in particular pieces of the code to other devs.

**Comment by tylerjereddy** [comment] 2015-08-09 17:56
TopologyGroups are still using methods for `types()` and `angles()` in 0.11 according to the docs? I see that atomgroups are now allowing access to `types` as a property instead. Is this consistent / as intended?

My initial parsing of the Python modules in the MDAnalysis package indicates that developers have generally been pretty thorough. I couldn't even find a spurious `selectAtoms`! However, I'm sure we can find some things that still need adjusting for `0.11` in the docs.

**Comment by richardjgowers** [comment] 2015-08-19 14:39
I wasn't sure with the `types()` method, it's more like a `keys()` method, so isn't a property, but it does conflict with the `AtomGroup.types` method.

With `angles()`, I think we're moving towards using `values()`, which has to be a method because it can accept periodic boundary information, and it also does lots of work computationally, so isn't like a property.

**Comment by dotsdl** [comment] 2015-09-05 06:40
Working on the AtomGroup docs in light of the changes to resids and friends in #385. Should be pushing changes before tomorrow ends.

**Comment by dotsdl** [comment] 2015-09-06 06:21
Looked through the core docs and made corrections in light of recent changes in #416.

**Closed** 2015-09-07 10:34 UTC
Labels: Component-Docs, Priority-Critical, usability
