### ISSUE TITLE
Regarding  MDAnalysis code for/to calculate hydrogen bond autocorrelation function

### ISSUE THREAD

**Issue by cy16f01** [MDAnalysis/mdanalysis#1576] opened 2017-08-03 05:16 UTC
Hello, 
I have done a MD simulation of glycine and water mixture as an example in gromacs, and now i need to calculate the hydrogen bond auto correlation function (HBond lifetime-intermittent and continuous).
I searched the program/code for HBond autocorrelation function of the following links, but i am not able to find out which is the right code to calculate the HBond auto correlation function - intermittent and continuous.
1] http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/waterdynamics.html#id2
2] http://www.mdanalysis.org/mdanalysis/documentation_pages/analysis/hbond_autocorrel.html
3] http://www.mdanalysis.org/mdanalysis/_modules/MDAnalysis/analysis/hbonds/hbond_autocorrel.html
which code in the following pages are the correct code in MDAnalysis library to write the code to calculate HBond auto correlation function - intermittent and continuous. ...
Can anybody help me regarding this....?? 

Thank you...

**Comment by orbeckst** [comment] 2017-08-03 21:51
Hi @cy16f01 , this issue is a duplicate of #1563 so I am closing this one.

**Closed by orbeckst** 2017-08-03 21:51 UTC
Labels: duplicate
