### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by anupama-creator** [MDAnalysis/mdanalysis#3123] opened 2021-02-18 05:25 UTC
I need mdanalysis package for analysis but unable to install it properly as i am new to it...
If anybody known or has encountered the similar issue kindly please guide me or suggest me to resolve.
Thanks in advance for the help.....

After running a command on terminal...... 
(mdaenv) sudip@water1:~$ pytest --disable-pytest-warnings --pyargs MDAnalysisTests

I got the following error.......

======================================================================= test session starts ========================================================================
platform linux -- Python 3.6.12, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/sudip
plugins: hypothesis-6.2.0
collected 0 items / 142 errors                                                                                                                                     

============================================================================== ERRORS ==============================================================================
_________________________________ ERROR collecting miniconda2/envs/mdaenv/lib/python3.6/site-packages/MDAnalysisTests/test_api.py __________________________________
miniconda2/envs/mdaenv/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:994: in _gcd_import
    ???
<frozen importlib._bootstrap>:971: in _find_and_load
    ???
<frozen importlib._bootstrap>:941: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
<frozen importlib._bootstrap>:994: in _gcd_import
    ???
<frozen importlib._bootstrap>:971: in _find_and_load
    ???
<frozen importlib._bootstrap>:955: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:665: in _load_unlocked
    ???
<frozen importlib._bootstrap_external>:678: in exec_module
    ???
<frozen importlib._bootstrap>:219: in _call_with_frames_removed
    ???
miniconda2/envs/mdaenv/lib/python3.6/site-packages/MDAnalysisTests/__init__.py:126: in <module>
    matplotlib.use('agg', warn=False)
E   TypeError: use() got an unexpected keyword argument 'warn'
____________________________ ERROR collecting miniconda2/envs/mdaenv/lib/python3.6/site-packages/MDAnalysisTests/analysis/test_align.py ____________________________
miniconda2/envs/mdaenv/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:994: in _gcd_import
.
.
.
.
.
.
.
.
.
.
ERROR miniconda2/envs/mdaenv/lib/python3.6/site-packages/MDAnalysisTests/utils/test_modelling.py - TypeError: use() got an unexpected keyword argument 'warn'
ERROR miniconda2/envs/mdaenv/lib/python3.6/site-packages/MDAnalysisTests/utils/test_persistence.py - TypeError: use() got an unexpected keyword argument 'warn'
ERROR miniconda2/envs/mdaenv/lib/python3.6/site-packages/MDAnalysisTests/utils/test_qcprot.py - TypeError: use() got an unexpected keyword argument 'warn'
ERROR miniconda2/envs/mdaenv/lib/python3.6/site-packages/MDAnalysisTests/utils/test_selections.py - TypeError: use() got an unexpected keyword argument 'warn'
ERROR miniconda2/envs/mdaenv/lib/python3.6/site-packages/MDAnalysisTests/utils/test_streamio.py - TypeError: use() got an unexpected keyword argument 'warn'
ERROR miniconda2/envs/mdaenv/lib/python3.6/site-packages/MDAnalysisTests/utils/test_transformations.py - TypeError: use() got an unexpected keyword argument 'warn'
ERROR miniconda2/envs/mdaenv/lib/python3.6/site-packages/MDAnalysisTests/utils/test_units.py - TypeError: use() got an unexpected keyword argument 'warn'
ERROR miniconda2/envs/mdaenv/lib/python3.6/site-packages/MDAnalysisTests/visualization/test_streamlines.py - TypeError: use() got an unexpected keyword argument ...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 142 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================= 142 errors in 3.19s ========================================================================

**Comment by RMeli** [comment] 2021-02-18 09:24
Hi @anupama-creator, the solution for this issue is described in #2938

**Comment by IAlibay** [comment] 2021-02-22 16:34
@anupama-creator did @RMeli's comment fix your issue? I have marked this issue as duplicate of #2938 and will close in a few days unless there are further issues.

**Comment by IAlibay** [comment] 2021-02-24 12:47
Closing as a stale duplicate. Please feel free to re-open @anupama-creator if necessary.

**Closed by IAlibay** 2021-02-24 12:47 UTC
Labels: duplicate
