### ISSUE TITLE
Remove usage of import * from tests

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#766] opened 2016-03-12 08:25 UTC
This is a bug causing #765 

```
find . -name '*.py' -exec grep 'testing import \*' {} +
./coordinates/test_reader_api.py:from numpy.testing import *
./coordinates/test_mol2.py:from numpy.testing import *
./coordinates/test_pdbqt.py:from numpy.testing import *
./test_units.py:from numpy.testing import *
./test_nuclinfo.py:from numpy.testing import *
./test_velocities_forces.py:from numpy.testing import *
```

All the uses of `from numpy.testing import *` (listed above) need to be replaced by explicit imports.  Should be an easy fix to get the hand of pull requests etc

**Comment by orbeckst** [comment] 2016-03-12 19:34
This needs to be fixed so that #765 can be resolved.

**Comment by orbeckst** [comment] 2016-03-12 19:36
Adde *Priority High* because not being able to run tests is bad.

**Comment by orbeckst** [comment] 2016-03-12 19:39
When you close this issue, also make sure that you either test if #765 is resolved or if you can't test for yourself, nicely ask the folks interested in #765 (like @rathann) to test again.

**Comment by abhinavgupta94** [comment] 2016-03-13 03:04
Since the error is on 0.14.0 version should  a PR be made on master branch?

**Comment by orbeckst** [comment] 2016-03-13 03:11
No, the PR should be against *develop*. The master branch contains released code.

**Comment by abhinavgupta94** [comment] 2016-03-13 06:49
The issue is fixed. Please check.

**Comment by abhinavgupta94** [comment] 2016-03-13 07:11
I am afraid this may not be the correct place to ask. But I got this urge to know. I installed MDAnalysis according to the [Development Branch](https://github.com/MDAnalysis/mdanalysis/wiki/DevelopmentBranch). I did `python setup.py develop` inside the package directory and then ran the same command inside the testsuite. But then if I change any file in the package directory, the change does not get reflected when I import and run some script. 
Should I not install testsuite or should I do it before installing package?

**Comment by jbarnoud** [comment] 2016-03-13 08:22
It is better to install the test suite before running it. When you install a package and plan to make changes on it, you can use `pip install -e <path-to-the-package>`. With the `-e` option, pip creates a link to the package rather than a copy, so your install get changed if you change the package.

**Closed** 2016-03-13 08:32 UTC
Labels: Difficulty-easy, Priority-High, testing
