### ISSUE TITLE
Move from Atom based topology to array based

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#363] opened 2015-07-22 09:08 UTC
This is something @dotsdl and I have been tinkering with.  Basically, it's changing the `AtomGroup` class to be a thin wrapper around a numpy array (rather than a list of `Atom`s).

The latest benchmark is here:
https://github.com/richardjgowers/atomgroup_olympics/blob/master/types2.ipynb
Dev list discussion:
https://groups.google.com/forum/#!topic/mdnalysis-devel/aHSB-ryCEQ0

We're seeing about 10-30x speedup for most common operations, so I think we can start to think about implementing this.  I think this Issue will act as an anchor for sub issues.

I think first thing to do is to make sure that tests currently cover everything, so we're confident that we aren't changing behaviour as we go.

**Comment by orbeckst** [comment] 2015-07-23 19:25
+1 (and we probably want this in a pre-1.0 milestone — either 0.12 or a 0.13 — just to make sure that we don't bake something into 1.0 that we haven't fully explored for a while)

**Comment by orbeckst** [comment] 2015-07-23 19:28
And more test coverage like #362 is definitely necessary before embarking on this in earnest.
We will also need tests that check in more detail what happens when AtomGroups are changed and how changes propagate.

**Comment by kain88-de** [comment] 2015-09-11 17:27
After having to add a new property to the Atom and AtomGroup class I can only say you should make the AtomGroup the base class for everything.  I noticed this funny thing that I read a whole array in `PrimitivePDBReader` and make that accessible via the 'TimeStep` object to the `Atom` class. Now remember atom can potentially access all the occupancy from all other atoms in the universe. But the code to access array in `AtomGroup` is

```python
@property
def some_metadata(self):
    return np.array([atom.metadata for atom in self.atoms])
```

This idiomatic  code (when `Atom` it the base of the Topology) has to be slow by design. I iterate over a class container to iterate over an array just to build a shallow copy of said array and return it.

```python
@property
def some_metadata(self):
        return self.ts.data['metadata'][self.atom_idx]
```

This should result in faster code by design in the end. We don't make hops between array in container classes. It gets much easier to set things correctly at the `AtomGroup` level. And it helps with the implicit assumption in the Readers that we work on whole frames.

**Comment by richardjgowers** [comment] 2015-09-11 18:28
Yep, you've pretty much hit the nail on the head for why we're changing this.  Plus once we've got everything in arrays it's statically typed.....

**Comment by richardjgowers** [comment] 2015-12-27 17:01
I think the content of this Issue is done, and now there's just lots of loose ends to tidy

**Comment by orbeckst** [comment] 2015-12-27 19:27
Awesome. 

However, can we do the 0.13.0 release *before* merging? We already have so many fixes and updates that I would like a stable and uptodate "old" release before switching over to the new system. 

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Dec 27, 2015 um 12:01 schrieb Richard Gowers <notifications@github.com>:

**Comment by dotsdl** [comment] 2015-12-27 20:28
Agreed. The release for 0.13.0 should *not* include this change, but should include among other things deprecation warnings for everything that will disappear when this gets merged (0.14.0).

**Comment by orbeckst** [comment] 2015-12-28 15:58
Can someone target this to a 0.14 milestone? 

I think we should leave this issue open until it is merged; my understanding of the issue tracker is that it reflects the status of the develop branch (although we never really discussed this an I'd be curious how other @MDAnalysis/coredevs see this).

**Comment by kain88-de** [comment] 2015-12-28 16:19
I agree with @orbeckst. If you have fixed an issue in a branch link to that branch or better create a PR with the `WIP` flag. That way it is visible that people work on it and where the solution is.

**Comment by dotsdl** [comment] 2015-12-28 17:17
I agree. This should stay open. Once `issue-363` gets merged into `develop` we can finally close the issue.

**Comment by orbeckst** [comment] 2015-12-29 02:29
See also the wiki page [Issue 363 changes](https://github.com/MDAnalysis/mdanalysis/wiki/Issue363-Changes) that @richardjgowers and @dotsdl set up.

**Comment by mnmelo** [comment] 2016-02-16 15:08
I'm starting to play with the new topology layout, regarding #175. What is now the recommended way to subclass `AtomGroup`?

Shall I add another entry to `classdict`, like this?
```python
AS = classdict['atomgroup'] = copy_class(
        'AtomSelection', AtomSelection, AG)
```

I have a couple more questions/comments regarding the dynamic creation of classes:
- The order of `*parents`, in `copy_class` is important. But in `classdict` population `GB` is always the first parent. Shouldn't it be the other way around, in case the `AtomGroup` or whatever other class wants to override attributes?

- From what I understand dynamic classes are only setup when a universe is created. What if in my script I want to subclass `AtomGroup` before that?

- Do the classes in `core/groups.py` really have to have the same name? Shouldn't they be `_AtomGroup`, for instance? When I ask for the MRO of a dynamically created class I get this:
```python
universe._classes['atomgroup'].__mro__
(MDAnalysis.core.groups.AtomGroup,
 MDAnalysis.core.groups.Group,
 MDAnalysis.core.groups.GroupBase,
 MDAnalysis.core.groups.AtomGroup,
 object)

# Hmm.. two MDAnalysis.core.groups.AtomGroup classes.
# But wait!
universe._classes['atomgroup'].__mro__[0] is universe._classes['atomgroup'].__mro__[-2]
False
# This is confusing...
```

(I know this is still WIP, but I'm struggling to grasp the need for dynamic creation of classes instead of having `AtomGroup` inherit directly from `GroupBase`. Is it to have all `*level` code in a single place? Apologies if this has already been explained somewhere else...)

**Comment by richardjgowers** [comment] 2016-02-16 17:34
Yeah that looks like the correct way to make AtomSelection.

Iirc, there's no name conflicts in GB / others, but yes you're probably right that we've probably got the ordering wrong.

Afaik you can't subclass AtomGroup before it exists with this new version.  Not something we had thought of before admittedly.

Yeah they should have a better name, `_AtomGroup` is good, unless we want them "public" for things like the above point.

The point of having everything dynamic is so that all the code related to, say, mass is in one module.  Once mass gets defined (usually by a parser), then all the mass related stuff gets loaded into the classes.  By not hacking the module version of AtomGroup, you can have two Universes with separate definitions of AtomGroup.

Thinking about it... we might be able to make this work without the dynamic classes, by instead "registering" the Attributes like we do Readers.  I'm not sure what this would lose/gain though.

**Comment by dotsdl** [comment] 2016-02-16 17:43
> Thinking about it... we might be able to make this work without the dynamic classes, by instead "registering" the Attributes like we do Readers. I'm not sure what this would lose/gain though.

You mean where `__getattr__` of, say, `AtomGroup` looks for names in the registry we've built, instead of the class having had these attached to it? I think that could work, but not sure if there are funny consequences to this. Basically the `Universe` an `AtomGroup` is attached to would have a registry of topology attributes instead of a registry of classes constructed from those attributes.

**Comment by dotsdl** [comment] 2016-02-16 17:46
> Yeah they should have a better name, _AtomGroup is good, unless we want them "public" for things like the above point.

The reason I named them conventionally was so that we can do things like `` :class:`AtomGroup` `` in the docs and sphinx will build the right directive. Not sure if it will work otherwise, but I admit it's confusing.

**Comment by dotsdl** [comment] 2016-02-16 17:55
@mnmelo the reason `AtomGroup` isn't subclassed from `GroupBase` explicitly is because [we add `TopologyAttr` properties to a Universe's own copy of `GroupBase` class](https://github.com/MDAnalysis/mdanalysis/blob/issue-363/package/MDAnalysis/core/universe.py#L386) (called `Group`), which is then subclassed to create the Universe's own `AtomGroup`, `ResidueGroup`, and `SegmentGroup` classes. The alternative would be to add these `TopologyAttr`s to each of those `*Group` classes and not give `Universe` its own `Group` at all, but the difference is adding `TopologyAttr`s three times vs. once.

**Comment by mnmelo** [comment] 2016-02-16 17:58
I see. I'll have to study this more to fully understand, but an immediate question: couldn't we register those `TopologyAttr` properties with the universe and then have the `*Group` classes access them through it?

**Comment by mnmelo** [comment] 2016-02-16 18:00
I also feel that this might be a good case for using `super` and a neat construction of new-style classes, but again, I must study it more in-depth.

**Comment by richardjgowers** [comment] 2016-02-16 18:04
@mnmelo I'm not sure this is the best reason, but adding the attributes to AtomGroup allows introspection in ipython which is nice.  I'm also guessing that going via `__getattr__` is a slower route.

**Comment by mnmelo** [comment] 2016-02-17 07:50
Ok, I finally wrapped my head around it (I think). I'm writing a summary here for the future researcher, and some ideas. Please give corrections/feedback.

(Note: where I write `AtomGroup` I generally mean other `*Group` classes too.)
Why dynamic class creation
-------------------------------------
- Not all `AtomGroups` are created alike. We want those from Universes with rich topologies to have more topology attributes than `AtomGroups` from simpler Universes.

- We also want the `AtomGroup` object to have the topology attributes itself, instead of just accessing them through the Universe (makes it easier to use `dir()` and IPython's context info/tab completion).

- This is done by having a base `AtomGroup` class and a base `GroupBase` class. The Universe copies to itself a subclass of `GroupBase` (called just `Group`). The final `AtomGroup` class that is used will be created on-the-fly by the Universe, inheriting from the base `AtomGroup` and the `Group` subclass.

- Why all this trouble? Because then the Universe can monkey-patch its specific `Group` class with the topology attributes it has, and all new `AtomGroups` come out working as intended.

Advantages
----------------
- Transparent handling of variable topology attributes.

- Monkey-patching the `Group` class only needs to be done once per Universe. Nothing more needs to be done upon `AtomGroup` initialization.

Disadvantages
--------------------
- Convoluted (unpythonic?) object model. Makes it hard to add functionality to `*Groups` via subclassing.

- Qualified names of the child classes become meaningless and confusing (see my comments above).

Alternatives?
------------------
There is an alternative way to achieve the same behavior while keeping a more pythonic class structure: one could have base `AtomGroups` inherit from `GroupBase`. Instantiation code then would take care of monkey-patching the `AtomGroup` _object_ (not the class) with the required topology attributes.

The main disadvantage of this is that monkey-patching would need to be done for every `AtomGroup` creation, which will incur in an overhead. The upshot is a great simplification of the current scheme.

I'll try to run some benchmarking, to gauge this tradeoff. My gut feeling is that it is a small overhead. (What is the status on unit tests in branch `issue-363`? Can I rely on them?)

**Comment by richardjgowers** [comment] 2016-02-17 08:46
@mnmelo that all looks correct to me.

Lots of the tests will fail on the issue-363 branch, you're probably best off just trying to load a Universe manually to test for now.

**Comment by dotsdl** [comment] 2016-02-17 20:01
> There is an alternative way to achieve the same behavior while keeping a more pythonic class structure: one could have base `AtomGroups` inherit from `GroupBase`. Instantiation code would then take care of monkey-patching the `AtomGroup` _object_ (not the class) with the required topology attributes.

> The main disadvantage of this is that monkey-patching would need to be done for every `AtomGroup` creation, which will incur in an overhead. The upshot is a great simplification of the current scheme.

Why don't we just explicitly subclass `AtomGroup` from `GroupBase` and then just modify the `AtomGroup` class. This would achieve the same result in terms of class structure as your proposal but without (what I imagine would definitely be) performance losses. Also, since you can't monkey patch properties on instances, we would have replace these with descriptors, so there would be a good deal of work to do.

In either case, so long as `AtomGroup` gets its properties from its host `Universe`, it is simply not possible to meaningfully subclass it. I'm not too concerned about this because I don't see a use case for subclassing it under the new scheme.

**Comment by mnmelo** [comment] 2016-02-17 20:27
Subclassing `AtomGroup` from `GroupBase` would already simplify the dynamical inheritance scheme, but wouldn't remove it entirely: each universe would still have to create a subclass/clone of `AtomGroup` to monkey-patch.

The current setup makes it easier on the monkey-patching because patching `Group` does it at once for all `*Groups`.

I was under the impression anything could be monkey-patched onto instances, but haven't really looked deep into it. If it can't, then my alternative is moot.

**Comment by mnmelo** [comment] 2016-02-21 04:21
Ok, did some studying and indeed, as @dotsdl pointed out my alternative does need to involve some tinkering. It requires a small modification on how data descriptors are handled, and I still think it is a good way to go (if performance isn't hit too hard). I'll work on implementing int against branch `issue-363` and you'll let me know what you think.

Read on for the nitty gritty of it.

The trick to monkey-patching properties is that they work due to the default behavior of `__getattribute__` and `__setattr__` (inherited by new-style classes from `object`). From the Python [Descriptor HowTo Guide](https://docs.python.org/2/howto/descriptor.html):
> `object.__getattribute__()` transforms `b.x` into `type(b).__dict__['x'].__get__(b, type(b))`

The issue with monkey patching properties is that, as per the above quote, the data descriptors are looked for in the _class'_ `__dict__`, not the instance's. That's why properties can only be patched onto classes. My simple workaround is to override `__getattribute__` (resp. `__setattr__`) in the following way:
```python
def __getattribute__(self, attr):
    try:
        return object.__getattribute__(self, "__dict__")[attr].__get__(self, self.__class__)
    except (KeyError, AttributeError):
        return object.__getattribute__(self, attr)
```
which does exactly the same as the default behavior, but looks first in the object's instance, and then defers to default behavior if unsuccessful.
(Stricter checking in `__getattribute__` is useful to prevent catching exceptions raised inside the property-decorated method; see example below).

A working example in the lines of what we need is as follows:
```python
class AtomGroup(object):
    def __init__(self):
        self.a = 1
        self.b = 2
        self.some_prop = TopologyAttr.some_prop
        self.some_method = TopologyAttr.some_method.__func__.__get__(self, self.__class__)

    def __getattribute__(self, attr):
        try:
            obj = object.__getattribute__(self, '__dict__')[attr]
        except KeyError:
            return object.__getattribute__(self, attr)
        if hasattr(obj, '__get__'):
            return obj.__get__(self, type(self))
        else:
            return object.__getattribute__(self, attr)

    def __setattr__(self, attr, val):
        try:
            obj = object.__getattribute__(self, '__dict__')[attr]
        except KeyError:
            return object.__setattr__(self, attr, val)
        if hasattr(obj, '__set__'):
            return obj.__set__(self, val)
        else:
            return object.__setattr__(self, attr, val)

class TopologyAttr(object):
    @property
    def some_prop(self):
        return self.a + self.b
    @some_prop.setter
    def some_prop(self, val):
        self.a = val - 1
        self.b = val + 1
    def some_method(self):
        return self.a - self.b

# Test it
a = AtomGroup()
print a.some_prop
# 3
print a.some_method()
# -1
a.some_prop = 10
print a.a, a.b
# 9 11
```

**Comment by dotsdl** [comment] 2016-02-21 05:40
@mnmelo I'm having trouble understanding what is gained by this scheme. Can you elaborate on why this would be better than the way the classes work now? From what I understand you'd still have a hard time meaningfully subclassing and then using your `AtomGroup` subclass under this scheme.

**Comment by mnmelo** [comment] 2016-02-21 10:49
I find the current implementation kludgy. It has a series of drawbacks I pointed out earlier that make extensibility hard to understand and implement.

On the particular aspect of `AtomGroup` subclassing: with my alternative I can simply do:
```python
class MyAtomGroup(AtomGroup):
    def mymethod(self):
        ...

# And later:
universe1 = ...
universe2 = ... # Different universes with different sets of TopologyAttrs
my_ag = MyAtomGroup(some_indices, universe1)
my_ag2 = MyAtomGroup(some_indices, universe2)
# Or if we implement a clever AtomGroup.__init__ that takes indices and
#  the universe from another AtomGroup:
my_ag = MyAtomGroup(existing_plain_vanilla_atomgroup)
```

See that `MyAtomGroup` can be defined at any time before a universe is loaded. There's also no extra work if I'm dealing with multiple universes.
It feels indistinguishable from standard behavior and would probably not break existing code that subclasses `AtomGroup`.

As it currently stands the above snippet would have to look something like:
```python
class MyAtomGroup(AtomGroup):
    def mymethod(self):
        ...

# And later:
universe1 = ...
universe2 = ... # Different universes with different sets of TopologyAttrs

MyAtomGroup1 = type(MyAtomGroup, universe1._classes['atomgroup'])
MyAtomGroup2 = type(MyAtomGroup, universe2._classes['atomgroup'])
# Or implement some sort of class factory

my_ag = MyAtomGroup1(some_indices, universe1)
my_ag2 = MyAtomGroup2(some_indices, universe2)
# The following wouldn't work without adding an extra layer
#   of bookkeeping to know which AtomGroup subclass to use.
my_ag = some_function_orClass(existing_plain_vanilla_atomgroup)
```
Not only does this put a large burden on the user looking into extending `AtomGroup`, it is already contributing to bloat in our own code, as we basically have to go through the same hoops ourselves.

Finally, I understand that dynamically subclassing, as is currently done, might be a way to deal with monkey patching, but it feels out-of-place in a project where we control all the classes.

**Comment by dotsdl** [comment] 2016-02-21 21:00
I think we shouldn't have to hack `__getattribute__` for this scheme to work, nor should if we can avoid it. Instead one can make property-like attributes for objects using descriptors: https://docs.python.org/2/howto/descriptor.html

**Comment by mnmelo** [comment] 2016-02-21 21:14
I thought the same, but as discussed in [SO](http://stackoverflow.com/questions/12599972/descriptors-as-instance-attributes-in-python) it seems to be per design that the default is to only look for descriptors at the class level, not instance level.

What we're trying to do here, either patch the class or the instance, already goes against the rationale for only having descriptors at class-level. Therefore, I think we have some sort of freedom (i.e. we're already hacking away, anyway)

They do have alternative ways in that SO thread. Seemed messier to me, but didn't read in depth.

**Comment by dotsdl** [comment] 2016-02-21 21:23
@mnmelo Ah, you're right. I knew that properties could only be done for classes but wasn't aware this extended to descriptors in general. :/

**Comment by kain88-de** [comment] 2016-04-12 14:22
From what I remember you said an `AtomGroup` now can't exists without a universe attached to it. Correct?

There are occasions where I want to have an `AtomGroup` which points to a specific frame in a trajectory without needing to create another universe. A `copy` like this would be convenient for this.

```python
import MDAnalysis as mda
from MDAnalysisTests.datafiles import PSF, DCD

u = mda.Universe(PSF, DCD)
first = u.atoms.copy()
u.trajectory[-1]
last = u.atoms.copy()
```

Currently I would need to create two universes that load the same files.  It would make code like [this](https://github.com/MDAnalysis/mdanalysis/blob/2612ae4aa90da4b3c4c5b38dd817d404adb6f2d4/package/MDAnalysis/analysis/contacts.py#L438) easier.

Is this already possible with the new schema that you have build now. How hard would it be to add this?

**Comment by richardjgowers** [comment] 2016-04-13 07:07
So all data is either stored in u.trajectory or u.topology now, so to do
what you want you can create a new Universe which shares the topology half
of Universe but had an independent Reader. So should be very possible, but
I'm not sure what the best mechanisms for making this available are.

**Comment by dotsdl** [comment] 2016-05-29 22:11
@richardjgowers happy to help shepherd this in. I think I'll have time to work on it again in earnest this June. *crosses fingers*

**Closed** 2016-11-07 11:08 UTC
Labels: API, Component-Core, Component-Topology, Difficulty-hard, performance, solved by 363
