### ISSUE TITLE
Test timeout on multiprocessing Pool XTC test  in  CI

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/mdanalysis#4475] opened 2024-03-01 00:08 UTC
We are getting a timeout on the following test, especially for py3.9 on #3608 

```
 def test_creating_multiple_universe_without_offset(temp_xtc, ncopies=3):
        #  test if they can be created without generating
        #  the offset simultaneously.
        #  The tested XTC file is way too short to induce a race scenario but the
        #  test is included as documentation for the scenario that used to create
        #  a problem (see PR #3375 and issues #3230, #1988)
    
        args = (GRO, str(temp_xtc))
        with multiprocessing.Pool(2) as p:
            universes = [p.apply_async(mda.Universe, args) for i in range(ncopies)]
>           universes = [universe.get() for universe in universes]
```

Is giving 

```
    def poll(self, flag=os.WNOHANG):
        if self.returncode is None:
            try:
>               pid, sts = os.waitpid(self.pid, flag)
E               Failed: Timeout >200.0s
****
```

Unsure if we need to increase timeout or if this is an issue as isn't happening elsewhere. Might also be a runner perf issue.

**Comment by IAlibay** [comment] 2024-03-01 09:29
@hmacdope I believe this is a duplicate of [#4215 ](https://github.com/MDAnalysis/mdanalysis/issues/4209)

I'm going to close this one if that's ok?

**Closed as completed by IAlibay** 2024-03-01 09:29 UTC
Labels: Continuous Integration
