### ISSUE TITLE
Nucleic acid naming convention on the termini

### ISSUE THREAD

**Issue by tclick** [MDAnalysis/mdanalysis#461] opened 2015-10-01 04:20 UTC
CHARMM36 in Gromacs uses an additional naming convention for nucleic acid residues that are either at the 3' or 5' end (DA5 or RU3), but MDAnalysis does not account for this. I recommend that this be added to the selection under 'nucleic'.

I'm currently using Python 2.7.10 and MDAnalysis 0.10 on Mac OSX 10.10

**Comment by hainm** [comment] 2015-10-01 07:19
can you say why you close this?

**Comment by tclick** [comment] 2015-10-01 07:45
I initially received a file from someone that had a different convention of naming the nucleic acid residues (e.g., DA instead of ADE). However, this seems to be a naming convention used in Gromacs by the CHARMM36 force field. Therefore, this may need to be reopened and changed to request the addition of the Gromacs naming convention.

**Comment by orbeckst** [comment] 2015-10-01 08:25
@tclick, can you please provide a small example file (attach to issue should work) + test code snippet?

**Comment by tclick** [comment] 2015-10-01 08:41
If I have a GRO file with DNA and RNA in it, the residues are labeled DT5, DA, DC, DG and RC5, RG, RU, RU. In MDAnalysis 0.10, if I issue the command 'sel = univ.selectAtoms('nucleic'); sel.resnames()', I receive a listing for all the residues minus the DT5 and RC5.

--
Cordially,
柯明 Timothy H. Click, Ph.D.
Department of Biological Science and Technology
Institute of Bioinformatics and Systems Biology
National Chiao Tung University
208 Lab Building 1, 75 Bo-Ai St.
Dong District, Hsinchu, Taiwan 30062
(R.O.C.)
886-3-5712121 x56997
tclick@nctu.edu.tw <mailto:tclick@nctu.edu.tw>

**Comment by orbeckst** [comment] 2015-10-02 08:30
@tclick , can you please add the link from your email to the mailing list where you posted this information or copy & paste it here. Ultimately, developers use the issue reports as clearing house for information and it is inconvenient having to go through the mailing list archive. This will ensure that the issue is addressed sooner. Thanks!

**Comment by tclick** [comment] 2015-10-03 07:21
@orbeckst, I'll do you even better than that. Here's the modified code from core/Selection.py (line 677)

    nucl_res = dict([(x, None) for x in [
        'ADE', 'URA', 'CYT', 'GUA', 'THY', 'DA', 'DC', 'DG', 'DT', 'RA',
        'RU', 'RG', 'RC', 'A', 'T', 'U', 'C', 'G', 'DA5', 'DC5', 'DG5', 'DT5',
        'DA3', 'DC3', 'DG3', 'DT3', 'RA5', 'RU5', 'RG5', 'RC5', 'RA3', 'RU3',
        'RG3', 'RC3']])

**Comment by richardjgowers** [comment] 2015-10-03 15:34
Hi Timothy

If you want to go one step further, you could put together a Pull Request and we could list you as an author.

https://github.com/MDAnalysis/mdanalysis/wiki/ContributingCode

**Comment by orbeckst** [comment] 2015-10-03 23:42
A PR would be very nice; the main thing to be done is to add a test case. 


Am Oct 3, 2015 um 8:34 schrieb Richard Gowers <notifications@github.com>:

**Comment by orbeckst** [comment] 2015-10-06 18:41
@tclick , in addition for a change to the core (which is the code snippet above) we also need a [test case](/MDAnalysis/mdanalysis/wiki/ContributingCode#test-cases) that checks the functionality. The first step is write a code snippet that does exactly that (e.g. an atom selection that finds something as opposed to nothing). Ideally, you can use a nucleic acid file that is already included in the test data. If we don't have that, we need a *small* example file that can be included. Then turn the test code snippet into a formal unit test in [test_atomselections.py](https://github.com/MDAnalysis/mdanalysis/blob/develop/testsuite/MDAnalysisTests/test_atomselections.py).

**Closed** 2016-01-25 11:11 UTC
Labels: Component-Selections, defect, help wanted, Priority-Low
