### ISSUE TITLE
ModuleNotFoundError: No module named 'hypothesis'

### ISSUE THREAD

**Issue by Muhammad-Ahsan-Rasheed** [MDAnalysis/mdanalysis#4106] opened 2023-03-30 18:54 UTC
## Expected behavior ##

Test should run in without error

## Actual behavior ##

===================================================== ERRORS =====================================================
____________________________ ERROR collecting MDAnalysisTests/formats/test_libdcd.py _____________________________ 
ImportError while importing test module 'C:\Users\HP\GSoC\mdanalysis\testsuite\MDAnalysisTests\formats\test_libdcd.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
..\..\testsuite\MDAnalysisTests\formats\test_libdcd.py:25: in <module>
    import hypothesis.strategies as strategies
E   ModuleNotFoundError: No module named 'hypothesis'
============================================ short test summary info ============================================= 
ERROR MDAnalysisTests/formats/test_libdcd.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
==================================== 7 skipped, 8 warnings, 1 error in 21.53s ==================================== 

**Python Version:** Python 3.10.9
**Dir:**  PS ..\mdanalysis\testsuite> 
**Test Command:** pytest --disable-pytest-warnings --pyargs MDAnalysisTests

## Current version of MDAnalysis ##

- Which version are you using? Development
- Which version of Python (`python -V`)? Python 3.10.9
- Which operating system? Windows

**Comment by IAlibay** [comment] 2023-03-30 18:56
@Muhammad-Ahsan-Rasheed how did you intsall MDAnalysisTests? The setup.py specifically has hypothesis as a dependency, so pip should have pulled it down if it wasn't available: https://github.com/MDAnalysis/mdanalysis/blob/bd8911d8b0715e37dad8d119a05c8ed57c7fdf8d/testsuite/setup.py#L192

**Comment by Muhammad-Ahsan-Rasheed** [comment] 2023-03-30 20:05
I install all dependencies using pip install -e package

**Comment by IAlibay** [comment] 2023-03-30 20:18
@Muhammad-Ahsan-Rasheed you also need to install the testsuite. MDAnalysis is composed of two separate Python libraries, the core MDAnalysis library (located under `package`), and the test MDAnalysisTest library (located used `testsuite`).

Please see the testsuite for more information: https://userguide.mdanalysis.org/stable/contributing_code.html#building-mdanalysis

I am closing this issue as not a bug, and would direct you to the mailing lists or the discord server as places to reach out for more information on installing the MDAnalysis and MDAnalysisTest libraries: https://www.mdanalysis.org/#participating

Please do re-open this issue if you think that there is indeed a bug which needs addressing.

**Closed as completed by IAlibay** 2023-03-30 20:18 UTC
