### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by avijain3** [MDAnalysis/mdanalysis#3125] opened 2021-02-19 09:11 UTC
Hey guys,
 I am new to MDAnalysis modules. I tried importing the module in Jupyter I encountered this issue- 

ImportError                               Traceback (most recent call last)
<ipython-input-2-4c4262a6b4c9> in <module>
----> 1 import MDAnalysis

C:\ProgramData\Anaconda3\lib\site-packages\MDAnalysis\__init__.py in <module>
    182 )
    183 
--> 184 from .lib import log
    185 from .lib.log import start_logging, stop_logging
    186 

C:\ProgramData\Anaconda3\lib\site-packages\MDAnalysis\lib\__init__.py in <module>
     38 from . import mdamath
     39 from . import distances  # distances relies on mdamath
---> 40 from . import NeighborSearch
     41 from . import formats
     42 from . import pkdtree

C:\ProgramData\Anaconda3\lib\site-packages\MDAnalysis\lib\NeighborSearch.py in <module>
     35 from MDAnalysis.lib.util import unique_int_1d
     36 
---> 37 from MDAnalysis.core.groups import AtomGroup, Atom
     38 
     39 

C:\ProgramData\Anaconda3\lib\site-packages\MDAnalysis\core\__init__.py in <module>
    463 from . import groups
    464 from . import selection
--> 465 from . import AtomGroup

C:\ProgramData\Anaconda3\lib\site-packages\MDAnalysis\core\AtomGroup.py in <module>
     26 from .groups import (Atom, AtomGroup, Residue, ResidueGroup, Segment,
     27                      SegmentGroup)
---> 28 from . import universe
     29 
     30 

C:\ProgramData\Anaconda3\lib\site-packages\MDAnalysis\core\universe.py in <module>
    126                      Atom, Residue, Segment,
    127                      AtomGroup, ResidueGroup, SegmentGroup)
--> 128 from .topology import Topology
    129 from .topologyattrs import AtomAttr, ResidueAttr, SegmentAttr
    130 

C:\ProgramData\Anaconda3\lib\site-packages\MDAnalysis\core\topology.py in <module>
     62 import numpy as np
     63 
---> 64 from .topologyattrs import Atomindices, Resindices, Segindices
     65 from ..exceptions import NoDataError
     66 

C:\ProgramData\Anaconda3\lib\site-packages\MDAnalysis\core\topologyattrs.py in <module>
     38 import Bio.Seq
     39 import Bio.SeqRecord
---> 40 import Bio.Alphabet
     41 from collections import defaultdict
     42 import copy

C:\ProgramData\Anaconda3\lib\site-packages\Bio\Alphabet\__init__.py in <module>
     19 
     20 raise ImportError(
---> 21     "Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information."
     22 )

ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.

P.S. I installed the library in conda environment via running the anaconda prompt in administrator mode.

Thanks

**Comment by IAlibay** [comment] 2021-02-19 15:38
@avijain3 what version of python are you running?

Also if you do `conda list` what is the version of MDAnalysis that is reporting?

This issue should have been fixed version 1.0.

**Comment by avijain3** [comment] 2021-02-20 08:41
The version that shows on `conda list` is 0.20.1 
This is the exact statement that pops on doing `conda list` "mdanalysis                0.20.1           py37h6538335_0    conda-forge"
The version of python that I use is 3.7.6

**Comment by IAlibay** [comment] 2021-02-20 16:07
@avijain3 the latest version on conda-forge should be 1.0.0 not 0.20.1.

I'm not sure why/how this is happening,

Going by your paths I assume this is on Windows? What does `conda search MDAnalysis -c conda-forge` return for you? I can see 1.0 via anaconda prompt on Win10.

**Comment by avijain3** [comment] 2021-02-21 12:52
These are the exact lines of code that appear
**```
(base) C:\WINDOWS\system32>conda search MDAnalysis -c conda-forge
Loading channels: done

# Name                       Version           Build  Channel
mdanalysis                    0.19.2 py36h6538335_1000  conda-forge
mdanalysis                    0.19.2  py36hfa6e2cd_0  conda-forge
mdanalysis                    0.19.2 py37h6538335_1000  conda-forge
mdanalysis                    0.20.0  py36h6538335_0  conda-forge
mdanalysis                    0.20.0  py37h6538335_0  conda-forge
mdanalysis                    0.20.1  py36h6538335_0  conda-forge
mdanalysis                    0.20.1  py37h6538335_0  conda-forge
mdanalysis                    0.20.1  py38h6538335_0  conda-forge
mdanalysis                     1.0.0  py36h003fed8_0  conda-forge
mdanalysis                     1.0.0  py36he2d232f_1  conda-forge
mdanalysis                     1.0.0  py36he2d232f_2  conda-forge
mdanalysis                     1.0.0  py37h1834ac0_0  conda-forge
mdanalysis                     1.0.0  py37hf2a7229_1  conda-forge
mdanalysis                     1.0.0  py37hf2a7229_2  conda-forge
mdanalysis                     1.0.0  py38h7ae7562_0  conda-forge
mdanalysis                     1.0.0  py38h885f38d_1  conda-forge
mdanalysis                     1.0.0  py38h885f38d_2  conda-forge
mdanalysis                     1.0.0  py39h415ef7b_1  conda-forge
mdanalysis                     1.0.0  py39h415ef7b_2  conda-forge
```**

**Comment by IAlibay** [comment] 2021-02-22 14:28
Looks like 1.0.0 is getting picked up by conda. It's hard to tell what the issue is but the fact that conda didn't pick up 1.0.0 could be down to some library conflict? I would suggest creating a new environment and trying to install MDAnalysis again.

@richardjgowers and @orbeckst (whom I think have the keys to the conda-forge stuff), we shouldn't have a py3.9 version of v1.0.0. It's completely untested. Is it worth marking them as broken so that folks don't try to install it?

**Comment by avijain3** [comment] 2021-02-24 12:16
So should I just install the MDAnalysis library or are there other libraries as well that need to be downloaded along with the MDAnalysis library i.e. would the MDAnalysis download all the dependencies on its own or do I have to download each other relevant libraries manually?

**Comment by IAlibay** [comment] 2021-02-24 12:47
Installing via `conda` will pick up all the dependencies required for normal operation although some optional packages like parmed will need to be installed separately, see here for more details: https://userguide.mdanalysis.org/stable/installation.html#conda

That being said, @avijain3 these are more usage questions and probably are best asked on the mailing list.

**Comment by IAlibay** [comment] 2021-03-01 18:27
@avijain3 is this good to be closed? If you're facing more installation issues please do let us know, otherwise I'll close this issue in a couple of days.

**Comment by avijain3** [comment] 2021-03-03 08:07
Hello,Thanks for the sameYes I could install it after setting a new environment and degrading the version of matplotlib.ThanksI guess we could close this issue.
Also, was thinking if I should list the steps in which the library is to be installed in this issue itself so that people who try to install it from scratch don't face the same problem again?

Sent from Yahoo Mail on Android 
 
  On Mon, 1 Mar 2021 at 23:57, Irfan Alibay<notifications@github.com> wrote:   


@avijain3 is this good to be closed? If you're facing more installation issues please do let us know, otherwise I'll close this issue in a couple of days.

**Comment by IAlibay** [comment] 2021-03-06 23:40
> Also, was thinking if I should list the steps in which the library is to be installed in this issue itself so that people who try to install it from scratch don't face the same problem again?

Any ways to improve our documentation is appreciated, but I think it might be best to open a separate issue for this @avijain3 (i.e. specifically highlighting how the docs/userguide need updating). I'm afraid it'll make it hard for the devs to try to keep up with this issue.

I'm going to close the issue for now, if you think it's too much trouble to open a new one, please do re-open this one and post your installation findings.

**Closed by IAlibay** 2021-03-06 23:40 UTC
Labels: close?
