### ISSUE TITLE
Clearer Failure Error or Returning Empty AtomGroup with Selections e.g. cyzone

### ISSUE THREAD

**Issue by yuxuanzhuang** [MDAnalysis/mdanalysis#3026] opened 2020-11-10 15:30 UTC
## Expected behavior ##

When using some selection syntax e.g. `sphzone`, `cyzone` for an empty selection, the error should be "You are selecting within an empty AtomGroup" or just return an empty group (like with `around`)

## Actual behavior ##

When using selection syntax e.g. `sphzone`, `cyzone` for a empty selection, the error is not clear enough.

## Code to reproduce the behavior ##

``` python
>>> import MDAnalysis as mda
>>> from MDAnalysis.tests.datafiles import PSF, DCD

>>> u = mda.Universe(PSF, DCD)
>>> ag = u.select_atoms('sphzone 10 resname blabla')

--> 333         ref = sel.center_of_geometry().reshape(1, 3).astype(np.float32)
    334         pairs = distances.capped_distance(ref, group.positions, self.cutoff,
    335                                           box=box,

ValueError: cannot reshape array of size 0 into shape (1,3)

>>> ag = u.select_atoms('cyzone 10 6 -6 resname blabla')

--> 349         vecs = group.positions - sel.center_of_geometry()
    350 
    351         if self.periodic and not np.any(group.dimensions[:3] == 0):

ValueError: operands could not be broadcast together with shapes (3341,3) (0,3)
```

while for `around`...

```python
>>> ag = u.select_atoms('around 10 resname blabla')
>>> ag
<AtomGroup with 0 atoms>
```
## Possible solution ##
I am in favor of just seeing an empty `AtomGroup` in these cases.

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`) 2.0.0-dev
- Which version of Python (`python -V`)? 3.8
- Which operating system? Ubuntu 18

**Comment by IAlibay** [comment] 2020-11-10 15:43
I believe this is the same as #2915?

**Comment by yuxuanzhuang** [comment] 2020-11-10 16:00
> I believe this is the same as #2915?

Oh right! Sorry I failed to catch it.

**Comment by IAlibay** [comment] 2020-11-10 16:12
> > I believe this is the same as #2915?
> 
> Oh right! Sorry I failed to catch it.

No worries, always a good reminder that it needs fixing :)

I'll leave it up to you as to whether you want to keep this issue open or close it (it looks like most of the important details are already echoed in #2915, but you'll know better).

**Comment by orbeckst** [comment] 2020-12-31 00:23
duplicate of #2915

**Comment by orbeckst** [comment] 2020-12-31 00:26
I am closing this issue in favor of #2915 and add a comment that additional detail can be found here.

**Closed by orbeckst** 2020-12-31 00:26 UTC
Labels: Component-Selections
