### ISSUE TITLE
DCD file reader EOF error

### ISSUE THREAD

**Issue by dkonstan** [MDAnalysis/mdanalysis#4057] opened 2023-03-07 14:43 UTC
In version 2.4 on Linux (a cluster running CentOS), the DCDReader often crashes with an EOF error. Usually the beginning of the trajectory is read ok, but after the beginning it crashes. To reproduce the error, just do

for ts in uni.trajectory:
    pass

until it crashes, which it should. This happens for any trajectory. This is for python 3.10. I reverted to version 2.1 and the issue went away.

**Comment by IAlibay** [comment] 2023-03-07 14:55
I suspect this is probably related to #4039? Does version 2.3 work for you @dkonstan ? We'll be releasing a patch release to fix this issue soon.

**Comment by dkonstan** [comment] 2023-03-07 15:07
Yes, that is most likely the issue. I will stick with 2.1 for now, it is
good enough for me, but will keep an eye out for the patch.

**Comment by orbeckst** [comment] 2023-03-07 15:58
Close as duplicate of #4039 ?

**Comment by chappertron** [comment] 2023-03-23 16:44
Perhaps it's not worth mentioning now if this is going to be closed, however, this may be helpful information.

I am experiencing a similar error, except it only occurs when slicing the trajectory. It always occurs at the same frame of a somewhat large (100,000 frames, 6.7 gb) trajectory. A minimal example is:

```python
u = mda.Universe("./test_data_files/lv300.data", "./test_data_files/dump300.dcd",)
for ts in u.trajectory[:-1]:
    print(ts.frame)
```

Always on the frame 29793, this gives the error:
```
File "MDAnalysis/lib/formats/libdcd.pyx", line 398, in MDAnalysis.lib.formats.libdcd.DCDFile.seek
OSError: DCD seek failed with DCD error=Normal EOF
```

Removing the indexing in the example above lets the trajectory run fine.

If it helps, the trajectory is of a pure water box generated from lammps. MDAnalysis version is 2.4.2 from pip in macOS arm64. The issue does not occur with 2.3.0.

**Comment by orbeckst** [comment] 2023-03-24 02:47
Thanks @chappertron , when have a 2.4.3 patch release, could you please try again to check if the error persists?

**Comment by chappertron** [comment] 2023-03-24 14:40
> Thanks @chappertron , when have a 2.4.3 patch release, could you please try again to check if the error persists?

@orbeckst I'll keep an eye out for the release!

**Comment by chappertron** [comment] 2023-03-30 15:11
@orbeckst This issue seems to be fixed for me! Thanks!

**Closed as completed** 2023-03-30 15:29 UTC
