### ISSUE TITLE
BAT analysis method applies improper torsion shift to proper torsions

### ISSUE THREAD

**Issue by tlfobe** [MDAnalysis/mdanalysis#3916] opened 2022-11-11 02:13 UTC
## Expected behavior ##
I was running into some problems changing some torsions using the BAT tool in MDAnalysis. I was getting inconsistent torsions from MDAnalysis.Universe.dihedrals and the output from the BAT method. I expected the identified torsions in the BAT method to have the same torsions calculated using MDAnalysis.Universe.dihedrals.values(), but I'm not seeing that behavior. 

## Actual behavior ##
Below is a code snippet where I ran into this issue. `test_ice` is a InternalCoordinateEditor object I wrote which organizes the output of the BAT object into torsions, angles and bond arrays.  The issue I'm seeing is that the `test_ice.torsions` don't match up with the torsions in the Universe object they were generated from. 
 ```python
for i in range(len(test_ice.torsion_ids)):
    print("index:", i)
    ice_torsion = test_ice.torsions[i] * 180 / np.pi
    print("ICE torsion:", test_ice.torsion_ids[i], ice_torsion)
    if test_ice.torsion_ids[i].split(" ") in test_all_torsions:
        t_index = test_all_torsions.index(test_ice.torsion_ids[i].split(" "))
        print("MDA Universe:", " ".join(test_all_torsions[t_index]), test_u.dihedrals[t_index].value())
    if test_ice.torsion_ids[i].split(" ")[::-1] in test_all_torsions:
        t_index = test_all_torsions.index(test_ice.torsion_ids[i].split(" ")[::-1])
        print("MDA Universe:", " ".join(test_all_torsions[t_index]), test_u.dihedrals[t_index].value())
    else:
        print("Torsion not present in MDA Universe")
```

```
index: 0
ICE torsion: C135 O14 C138 O15 -4.108886978165111
MDA Universe: C135 O14 C138 O15 -4.108886978165118
Torsion not present in MDA Universe
index: 1
ICE torsion: C134 C135 O14 C138 -178.12294664824458
MDA Universe: C134 C135 O14 C138 -178.12294664824458
Torsion not present in MDA Universe
index: 2
ICE torsion: H118 C134 C135 O14 -179.81399685338377
MDA Universe: O14 C135 C134 H118 -179.81399685338377
index: 3
ICE torsion: H119 C134 C135 O14 120.14894112284682
MDA Universe: O14 C135 C134 H119 -59.66505573053691
index: 4
ICE torsion: H120 C134 C135 O14 -120.25601147070904
MDA Universe: O14 C135 C134 H120 59.92999167590721
...
```

I think what's happening is the shift applied for improper torsions isn't being correctly applied in some cases, causing this improper shift to be applied to proper torsions. For this molecule I'm working with I'm pretty certain that all the torsions used in the BAT method are proper torsions, so would not need the shift term added to them.
https://github.com/MDAnalysis/mdanalysis/blob/4a6aee43515db6b954281efdf6d7092ec58452e2/package/MDAnalysis/analysis/bat.py#L419

I went ahead and removed this shift term from my comparison script above and was able to get the torsions to match.
```python
shift = test_ice.torsions[test_ice.bat._primary_torsion_indices]
shift[test_ice.bat._unique_primary_torsion_indices] = 0

for i in range(len(test_ice.torsion_ids)):
    print("index:", i)
    ice_torsion = (test_ice.torsions[i] + shift[i]) * 180 / np.pi
    ice_torsion = ((ice_torsion + 180) % (2 * 180)) - 180
    print("ICE torsion:", test_ice.torsion_ids[i], ice_torsion)
    if test_ice.torsion_ids[i].split(" ") in test_all_torsions:
        t_index = test_all_torsions.index(test_ice.torsion_ids[i].split(" "))
        print("MDA Universe:", " ".join(test_all_torsions[t_index]), test_u.dihedrals[t_index].value())
    if test_ice.torsion_ids[i].split(" ")[::-1] in test_all_torsions:
        t_index = test_all_torsions.index(test_ice.torsion_ids[i].split(" ")[::-1])
        print("MDA Universe:", " ".join(test_all_torsions[t_index]), test_u.dihedrals[t_index].value())
    else:
        print("Torsion not present in MDA Universe")
```
```
index: 0
ICE torsion: C135 O14 C138 O15 -4.108886978165117
MDA Universe: C135 O14 C138 O15 -4.108886978165118
Torsion not present in MDA Universe
index: 1
ICE torsion: C134 C135 O14 C138 -178.12294664824458
MDA Universe: C134 C135 O14 C138 -178.12294664824458
Torsion not present in MDA Universe
index: 2
ICE torsion: H118 C134 C135 O14 -179.81399685338377
MDA Universe: O14 C135 C134 H118 -179.81399685338377
index: 3
ICE torsion: H119 C134 C135 O14 -59.66505573053695
MDA Universe: O14 C135 C134 H119 -59.66505573053691
index: 4
ICE torsion: H120 C134 C135 O14 59.92999167590722
MDA Universe: O14 C135 C134 H120 59.92999167590721
...
```

## Code to reproduce the behavior ##
This is the test system I was working with which gives this error.
Structure file: [em_mop_hexamer.gro.txt](https://github.com/MDAnalysis/mdanalysis/files/9985644/em_mop_hexamer.gro.txt)
Topology file: [terphenyl_mop_hexamer.itp.txt](https://github.com/MDAnalysis/mdanalysis/files/9985659/terphenyl_mop_hexamer.itp.txt)

``` python
import MDAnalysis as mda
import numpy as np
from MDAnalysis.analysis.bat import BAT

u = mda.Universe("terphenyl_mop_hexamer.itp", "em_mop_hexamer.gro")
selected_atoms = u.select_atoms("all")

bat = BAT(selected_atoms)
bat.run()

# Root atoms information
root_atoms = bat.results.bat[0:3]
root_ext_angles = bat.results.bat[3:6]
root_ics = bat.results.bat[6:9]

# Torsions and atom names
n_torsions = len(bat._torsions)
bat_torsions = bat.results.bat[0,9 + 2*n_torsions:]
bat_torsion_ids = [list(torsion.names) for torsion in bat._torsions]

# Torsion IDs in Universe.dihedrals
all_u_dihedrals = [[atom.name for atom in dihe.atoms] for dihe in u.dihedrals]

# Comparing torsions from each method
for i in range(len(bat_torsion_ids)):
    if bat_torsion_ids[i] in all_u_dihedrals:
        print("Index", i)
        torsion_index = all_u_dihedrals.index(bat_torsion_ids[i])
        print(bat_torsions[i] * 180 / np.pi, u.dihedrals[torsion_index].value())
    if bat_torsion_ids[i][::-1] in all_u_dihedrals:
        print("Index", str(i) + "*")
        torsion_index = all_u_dihedrals.index(bat_torsion_ids[i][::-1])
        print(bat_torsions[i] * 180 / np.pi, u.dihedrals[torsion_index].value())
....
```

## Current version of MDAnalysis ##
mdanalysis 2.2.0

- Which version are you using? 2.20
- Which version of Python (`python -V`)? Python 3.9.12
- Which operating system? Ubuntu 20.04.5 LTS

**Comment by orbeckst** [comment] 2022-11-11 20:58
@daveminh could you please have a look, given that you wrote the BAT module? Thanks.

**Comment by orbeckst** [comment] 2022-11-11 21:02
Thank you for the detailed report @tlfobe . I pinged the original author and I hope he can provide some help.

I noticed that you used MDA 2.2.0. Although I don't _think_ that there were any changes/fixes in 2.3.0 (or the upcoming 2.4.0), could you check that you see the same behavior with the latest released version?

**Comment by tlfobe** [comment] 2022-11-11 21:16
Thanks for the response! I made a fresh conda environment with MDA 2.3.0 and I see the same issue with running the minimum example above. I also put these files and my conda environment in this tar.gz file
[mdanalysis_bat_testing.tar.gz](https://github.com/MDAnalysis/mdanalysis/files/9993249/mdanalysis_bat_testing.tar.gz)

**Comment by tlfobe** [comment] 2022-11-28 22:24
Hello! Just pinging this again! For now, I'm using the workaround I show above in my code to get around this (removing the `shift` array from the BAT torsions)

**Comment by orbeckst** [comment] 2022-11-28 23:16
Thank you for checking 2.3.0, @tlfobe . Sorry, the issue slipped of my radar.

@daveminh could you or someone from your group please look at this issue? With contributed code it is really important to us that the original authors weigh in on potential bug reports.

**Comment by orbeckst** [comment] 2022-12-01 16:21
@tlfobe I reached out to the original author via email.

I am sorry that you are not getting a good response here. This is fairly specialized code and for anyone who hasn't really written the code it takes time to dig into it... time that is often spent on other urgent matters (typically not even MDAnalysis related). 

I am glad that you found a workaround for you. I would like the code in MDA to be fixed but I am lacking the expertise with the BAT code (or time to dig into it) to understand if the shift array should always be removed or why it's there in the first place. Maybe some people who routinely play with small molecules such as @lilyminium @richardjgowers may have some input, especially as you are comparing _within_ MDAnalysis.

**Comment by daveminh** [comment] 2022-12-01 19:34
This is not a bug in the code. I believe that it is a misunderstanding of the term "improper torsion", which is used differently than in the AMBER force field.

Fortunately, the documentation already describes what it meant by "improper torsion". If you consult Fig. 1 of Hikiri et al., 2016 (https://pubs.acs.org/doi/10.1021/acs.jctc.6b00563), it will make sense right away. The reasoning for this choice of "improper torsion" is also described in the documentation: https://github.com/MDAnalysis/mdanalysis/blob/4a6aee43515db6b954281efdf6d7092ec58452e2/package/MDAnalysis/analysis/bat.py#L47-L49.

**Comment by daveminh** [comment] 2022-12-01 19:36
Removing this shift would lead to a number that is consistent with the classic definition of a torsion, but all torsions with the same two central atoms would be highly correlated.

**Comment by tlfobe** [comment] 2022-12-01 20:28
Ah, I see now, so this is an issue where I was using classic definitions of torsions but the `BAT` module returns some torsions converted to improper torsions.

Perhaps a little confusing since the `BAT._torsions` list still has the atom names defined in the proper torsion definitions used. I was using the BAT module as a way to construct a Z-matrix for a system, manipulate the torsions and then reconstruct it to Cartesian coordinates. From what I'm familiar with Z-matrices are defined with all proper torsions, so easy to see why I got confused here.

In the paper you sent reducing the correlation between torsions was important for the BQH method, but for my uses, it doesn't make a significant difference if torsions are correlated or not.

Thanks for the clarification!

**Comment by orbeckst** [comment] 2023-01-03 23:14
I am closing this issue. Thank you @daveminh for clarifying the question.

If anyone thinks we need to improve the docs then please add a comment with a suggestion and I will re-open the issue.

**Closed as completed by orbeckst** 2023-01-03 23:14 UTC
Labels: Component-Docs, Component-Analysis
