### ISSUE TITLE
too many open files makes AtomGroup.sequence tests fail on MacOS?

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/mdanalysis#853] opened 2016-05-16 09:29 UTC
The minimal (but not full) build is failing tests because of the `sequence` method which is leaning on Biopython.  It looks like something has changed in that package, so depending on which version we build off we sometimes get failures

**Comment by jbarnoud** [comment] 2016-05-16 10:22
Do you have the traceback of the failure, and the version of BioPython with with the test fails?

**Comment by richardjgowers** [comment] 2016-05-16 10:25
https://travis-ci.org/MDAnalysis/mdanalysis/jobs/130391480

This is an example of a failed build, but here it's the full build.  More recent develop builds seem to pass now, so maybe it's just Bio was strange for a day?

**Comment by jbarnoud** [comment] 2016-05-16 19:03
I tried to reproduce the issue on my mac, and I could not. It could be a hiccup on travis. We should find out what cause them.

Just to keep track of the error, I copy paste here a representative sample of the errors:

```
======================================================================

ERROR: test_sequence_Seq (MDAnalysisTests.test_atomgroup.TestAtomGroup)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysisTests/test_atomgroup.py", line 441, in test_sequence_Seq

    s = p.residues.sequence(format="Seq")

  File "/Users/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysis/core/AtomGroup.py", line 1655, in sequence

    import Bio.Seq

  File "/Users/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/Bio/Seq.py", line 27, in <module>

    from Bio._py3k import range

ImportError: cannot import name range

-------------------- >> begin captured logging << --------------------

MDAnalysis.topology.PSF: DEBUG: PSF file /Users/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysisTests/data/adk.psf: format STANDARD

MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading /Users/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysisTests/data/adk_dims.dcd...

--------------------- >> end captured logging << ---------------------



======================================================================

ERROR: test_sequence_SeqRecord (MDAnalysisTests.test_atomgroup.TestAtomGroup)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/Users/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysisTests/test_atomgroup.py", line 428, in test_sequence_SeqRecord

    description="EcAdK from pdb 4AKE")

  File "/Users/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysis/core/AtomGroup.py", line 1655, in sequence

    import Bio.Seq

ImportError: No module named Seq

-------------------- >> begin captured logging << --------------------

MDAnalysis.topology.PSF: DEBUG: PSF file /Users/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysisTests/data/adk.psf: format STANDARD

MDAnalysis.core.AtomGroup: DEBUG: Universe.load_new(): loading /Users/travis/build/MDAnalysis/mdanalysis/miniconda/envs/pyenv/lib/python2.7/site-packages/MDAnalysisTests/data/adk_dims.dcd...

--------------------- >> end captured logging << ---------------------
```

**Comment by jbarnoud** [comment] 2016-06-10 08:14
Recently, the full build on OS X tends to fail with random import errors and random errors opening files. The other builds succeed. On the contrary to the most recent travis hic ups, these ones seems not to be fixed by rerunning the failing builds.

Here is an excerpt of such a failing build: https://gist.github.com/jbarnoud/7bf7f61f12f8f4cdc42f6d595cb36eae

The errors seem to be concentrated at the end of the build and can all be related somehow to IO. This would lean toward @richardjgowers hypothesis that we have to many files open at the same time.

**Comment by kain88-de** [comment] 2016-06-10 08:24
Great that you can reproduce this locally. Is there a way to monitor the number of open file descriptors on mac?

**Comment by jbarnoud** [comment] 2016-06-10 09:25
On 10/06/16 10:24, kain88-de wrote:
>
> Great that you can reproduce this locally. Is there a way to monitor 
> the number of open file descriptors on mac?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/MDAnalysis/mdanalysis/issues/853#issuecomment-225121962>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ABUWulTpQiaYdLQ7Eph8X-RRhEVTr7fYks5qKR8ogaJpZM4IfK2u>.
>
I did not reproduced it locally. The gist is a copy of travis log.

There are ways to list the open file descriptors in python: 
<http://stackoverflow.com/questions/20106220/check-for-open-files-with-python-in-linux>. 
The stackoverflow answer is about linux, but it should work on mac as 
well. It would be interesting to have the list of open file descriptor 
printed by nose when a test fails or errors.

**Comment by kain88-de** [comment] 2016-06-10 11:21
I'm not that deep into nose. I have no idea if they have a hook for failures. But this thing is hard to debug anyway with the sporadic errors, being on a remote makes it even harder.

**Comment by jbarnoud** [comment] 2016-06-10 11:22
On 10/06/16 13:21, kain88-de wrote:
>
> I'm not that deep into nose. I have no idea if they have a hook for 
> failures. But this thing is hard to debug anyway with the sporadic 
> errors, being on a remote makes it even harder.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://github.com/MDAnalysis/mdanalysis/issues/853#issuecomment-225157484>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ABUWur13vE5uiunozxB0kKXwGxEmX3Iqks5qKUimgaJpZM4IfK2u>.
>
I am working on a nose plugin to display a list of the open files upon 
test failure. No guarantee that I'll manage to have something working, 
though.

**Comment by mnmelo** [comment] 2016-06-10 11:34
I'm glad to give input. What's the strategy you're using?
Parallelization might complicate matters, but we might not be able to see the problem without it...

**Comment by richardjgowers** [comment] 2016-06-10 12:04
Iirc, there was a way to set the maximum number of file handles?  A way to reproduce this locally would be to set this low, say 4? (enough for a single test), and then see if it gets triggered.

https://docs.python.org/2/library/resource.html#resource.RLIMIT_NOFILE

This looks like the place to start... but it seems a little hacky so maybe there's a nicer approach.

**Comment by orbeckst** [comment] 2016-06-10 21:12
The tests for HOLE reduce open file descriptors to trigger #129 – look there.

**Comment by kain88-de** [comment] 2016-06-12 13:10
After playing around a little bit with reference counting and the garbage collector I'm starting to believe we have some cyclic references that can't be detected by the garbage collector for the universe object.

For the normal Reader objects I can detect when the reference count is at 0 (print a message with the `__del__` function. I'm not able to do this for the universe object.

**Comment by kain88-de** [comment] 2016-06-12 13:27
OK the reason is that our WeakReference Cache `MDAnalysis._anchor_universe` keeps the universe objects alive. Why do we have those WeakReference caches? @dotsdl from the comments around the code this looks like it has something to do with pickling the universe objects.

**Comment by kain88-de** [comment] 2016-06-12 16:22
Ok I found a minimal script to reproduce the open file descriptors nearly all the time.

```python
>>> import MDAnalysis as mda
>>> from MDAnalysisTests.datafiles import PSF, DCD
>>> import psutil
>>> import os
>>> import gc

>>> u = mda.Universe(PSF, DCD)
>>> u = None
>>> # there is no garbage to collect all fine
>>> gc.garbage
[ ]

>>> p = psutil.Process(os.getpid())
>>> # but wait the file is still open ???
>>> for f in p.open_giles(): print f.path
...
path/to/test.dcd

>>> # we still have a reference to the universe (weak)
>>> len(mda._anchor_universes)
1

>>> # hm but there is garbage to collect??
>>> gc.collect()
4005

>>> # the weak ref is gone now and the file is closed as well.
>>> len(mda_anchor_universes)
0
```

This has two consequences. 

1. our memory-leak test doesn't work
2. we keep some hard references alive through the usage of weak_references

This isn't that good. This means there isn't a clear way to detect memory leaks that we can rely on and our weak_references keep the universes unnecessarily alive.

**Comment by orbeckst** [comment] 2016-06-12 17:03
IIRC @mnmelo had added it so that AromGroups become picklable. 

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Jun 12, 2016 um 6:27 schrieb kain88-de <notifications@github.com>:

**Comment by kain88-de** [comment] 2016-06-12 17:06
BTW is should also be noted that there are occasions where manually doing a garbage collect doesn't clear the weak_reference cache leaving the files open indefinitely.

**Comment by mnmelo** [comment] 2016-06-13 10:03
Hmm, this is really unexpected because the whole point of weakrefs is to let referring objects die.

I'll check it.

**Comment by kain88-de** [comment] 2016-06-13 10:15
The best way I found so far to reproduce universes that can't be garbage collected is to run the testsuite in a interactive session (1 process). Then you can inspect the weakreference cache and the reference count of the objects inside of the cache.

**Comment by jbarnoud** [comment] 2016-06-13 10:27
@mnmelo The references that seem to keep the Universe alive seem to be the `self._universe` in the `Atom` class. Is it supposed to be a weak reference? Then why are the atoms still alive?

Anyway, the problem might be fixed with #363. I'll run the tests on that branch.

**Comment by richardjgowers** [comment] 2016-06-13 10:33
363 will still have objects (Atom, AG etc) pointing to Universe, so I think
we will have the same problem there.

It might be the circular link between universe's list of atoms and atom's
pointer back to Universe? Could definitely sprinkle weakref on every
pointer to the "master" Universe.

**Comment by kain88-de** [comment] 2016-06-13 10:42
There are much less reference in the #363 branch. But I also think the problem will still exists in there.

The atoms are also strongly referencing their parent universe currently. But that doesn't always keep the universe from being garbage collect as shown in the example script above.

**Comment by dotsdl** [comment] 2016-06-13 22:13
Are the failures due to open file descriptors for the trajectory readers (#239)? Or are we keeping open file descriptors for topology parsers, too? We don't keep topology parser file descriptors open in #363, for what it's worth.

**Comment by kain88-de** [comment] 2016-06-14 04:04
We don't do that either right now only trajectories.

**Comment by jbarnoud** [comment] 2016-06-14 06:51
Base on #874 and #874, only the readers keep files open.

**Comment by mnmelo** [comment] 2016-06-14 12:07
This is quite fishy, as neither AtomGroups nor Universes have `__del__` methods, and therefore should always be garbage-collected properly.

Readers do have `__del__`. I'll inspect those to see whether we're missing a leak somewhere.

**Comment by jbarnoud** [comment] 2016-06-15 09:26
I had the universe nose plugin (#879) draw a graph of the backward reference graph for one of the surviving `Atom` instances using the [objgraph](http://objgraph.readthedocs.io/en/stable/). See image bellow.

![backrefs](https://cloud.githubusercontent.com/assets/1382074/16074367/757029a0-32ea-11e6-997f-687230e30ee5.png)

It seems that the `Segment` class has several references (mostly indirect) to `Atom` instances. Since `Atom`s also reference `Segment`s, the references are circular. One cycle is `segment._residues` is a list of `Residue`s, `residue._container` is a list of `Atom`s, and `Atom`s refer to `Segment`s. An other cycle is due to `segment._cache['residues']._residues`, but also `segment._cache['residues']._cache['residues']._residues` being list of `Residue`s.

Have a look at the figure, it only accounts for 10 levels of back references starting from one `Atom` instance (red border and red font, top center of the figure) but the intricacies are scary.

**Comment by jdetle** [comment] 2016-06-15 09:31
Jonathan, that graph is terrifying...
On Wed, Jun 15, 2016 at 2:26 AM Jonathan Barnoud <notifications@github.com>
wrote:

> I had the universe nose plugin (#879
> <https://github.com/MDAnalysis/mdanalysis/pull/879>) draw a graph of the
> backward reference graph for one of the surviving Atom instances using
> the objgraph <http://objgraph.readthedocs.io/en/stable/>. See image
> bellow.
>
> [image: backrefs]
> <https://cloud.githubusercontent.com/assets/1382074/16074367/757029a0-32ea-11e6-997f-687230e30ee5.png>
>
> It seems that the Segment class has several references (mostly indirect)
> to Atom instances. Since Atoms also reference Segments, the references
> are circular. One cycle is segment._residues is a list of Residues,
> residue._container is a list of Atoms, and Atoms refer to Segments. An
> other cycle is due to segment._cache['residues']._residues, but also
> segment._cache['residues']._cache['residues']._residues being list of
> Residues.
>
> Have a look at the figure, it only accounts for 10 levels of back
> references starting from one Atom instance (red border and red font, top
> center of the figure) but the intricacies are scary.
>
> —
> You are receiving this because you are subscribed to this thread.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/MDAnalysis/mdanalysis/issues/853#issuecomment-226135209>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKcARie1Dw27KjFz5GBswLpuz8nEhDE7ks5qL8VggaJpZM4IfK2u>
> .
>
-- 
Have a wonderful day,
John J. Detlefs

**Comment by jbarnoud** [comment] 2016-06-15 10:13
It is much better with the #363 branch:

```
By the end of the tests, there are 158 open handle for 6 files:
* (27) /Users/jon/Envs/mda2/lib/python2.7/site-packages/MDAnalysisTests/data/coordinates/test.xyz.bz2
* (17) /Users/jon/Envs/mda2/lib/python2.7/site-packages/MDAnalysisTests/data/adk_oplsaa.xtc
* (27) /Users/jon/Envs/mda2/lib/python2.7/site-packages/MDAnalysisTests/data/coordinates/test.xyz
* (18) /Users/jon/Envs/mda2/lib/python2.7/site-packages/MDAnalysisTests/data/adk_oplsaa.trr
* (68) /Users/jon/Envs/mda2/lib/python2.7/site-packages/MDAnalysisTests/data/adk_dims.dcd
* (1) /Users/jon/dev/mdanalysis/testsuite/MDAnalysisTests/MDAnalysis.log


There are 0 living Universes at the end of the tests.
```

This means two things: the #363 branch does delete the Universes as expected. We have files open even if the Universe is gone.

**Comment by richardjgowers** [comment] 2016-06-15 10:15
So maybe it's just Readers for those formats need better closing of files?

**Comment by mnmelo** [comment] 2016-06-15 10:40
Regarding the circular references in the graph, Segments or Atoms don't have any `__del__` method, which means they should be easily garbage-collected. On the other hand, out-of-scope doesn't immediately mean garbage-collected, which means we might have lingering objects because garbage collection hasn't yet kicked in. The memleak plugin forces a garbage collection round at the end of each test, so if the plugin is active each test will be automatically cleaned up.

I second @richardjgowers that it is probably some readers that don't clean-up properly in their own `__del__`

**Comment by kain88-de** [comment] 2016-06-15 10:46
Nope i checked the readers they clean up nicely without a problem.

**Comment by richardjgowers** [comment] 2016-06-15 10:54
@jbarnoud are you running a manual garbage collect before detecting those 158 handles?

**Comment by jbarnoud** [comment] 2016-06-15 11:13
Since the initial hypothesis was that the tests failed because of too many open files, I did not trigger the gc before counting the open files. 

I reran the tests on the issue-363 branch with a `gc.collect()` before listing the open files. There are still open files.

```
By the end of the tests, there are 171 open handle for 7 files:
* (3) /Users/jon/dev/mdanalysis/testsuite/MDAnalysisTests/data/adk_dims2.dcd
* (27) /Users/jon/dev/mdanalysis/testsuite/MDAnalysisTests/data/coordinates/test.xyz
* (5) /Users/jon/dev/mdanalysis/testsuite/MDAnalysisTests/data/watdyn.dcd
* (74) /Users/jon/dev/mdanalysis/testsuite/MDAnalysisTests/data/adk_dims.dcd
* (27) /Users/jon/dev/mdanalysis/testsuite/MDAnalysisTests/data/coordinates/test.xyz.bz2
* (18) /Users/jon/dev/mdanalysis/testsuite/MDAnalysisTests/data/adk_oplsaa.trr
* (17) /Users/jon/dev/mdanalysis/testsuite/MDAnalysisTests/data/adk_oplsaa.xtc


There are 0 living Universes at the end of the tests.
There are 0 living atoms.
There are 305 living readers.
```

**Comment by orbeckst** [comment] 2016-07-21 20:02
Is this something that might deserve the "solved by 363" tag?

(I also renamed the issue because from the title it was not clear that this is the central point of discussion for the open file descriptor issues that we are seeing during testing – see also PR #901.)

**Comment by orbeckst** [comment] 2017-06-14 00:57
I am not really sure what to do with this issue. It looks at general problems with open files (such as #875 ) and it contains good research. But I don't really know what should be fixed and what the desired solution is.

Anyone else has an opinion?

**Comment by orbeckst** [comment] 2017-07-10 03:00
This does not seem to be a problem anymore (maybe pytest is not keeping as many objects around).... or if it is, please reopen.

**Closed by orbeckst** 2017-07-10 03:00 UTC
Labels: Component-Core, testing

**Comment by kain88-de** [comment] 2017-07-10 09:05
We increase the limit of open files for osx builds on travis. This might still be a problem. But we also figured out that nose artificially forced us to keep objects around longer then necessary.
