### ISSUE TITLE
Fails to make a universe from 4BXW.pdb

### ISSUE THREAD

**Issue by kaceyreidy** [MDAnalysis/mdanalysis#937] opened 2016-08-15 21:30 UTC
When a universe should be created, a ZeroDivisionError is raised.

---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-506-c48c17832ad6> in <module>()
----> 1 mda.Universe(path + '4BXW.pdb')

/usr/local/lib/python2.7/dist-packages/MDAnalysis/core/AtomGroup.pyc in __init__(self, *args, **kwargs)
   4337         try:
   4338             with parser(self.filename, universe=self) as p:
-> 4339                 self._topology = p.parse()
   4340         except IOError as err:
   4341             raise IOError("Failed to load from the topology file {0}"

/usr/local/lib/python2.7/dist-packages/MDAnalysis/topology/PDBParser.pyc in parse(self)
     88         structure['atoms'] = atoms
     89 
---> 90         bonds = self._parsebonds(atoms)
     91         structure['bonds'] = bonds
     92 

/usr/local/lib/python2.7/dist-packages/MDAnalysis/topology/PDBParser.pyc in _parsebonds(self, atoms)
    179             lines = (line for line in f if line[:6] == "CONECT")
    180             for line in lines:
--> 181                 atom, atoms = _parse_conect(line.strip())
    182                 for a in atoms:
    183                     bond = tuple([mapping[atom], mapping[a]])

/usr/local/lib/python2.7/dist-packages/MDAnalysis/topology/PDBParser.pyc in _parse_conect(conect)
    211     atom_id = np.int(conect[6:11])
    212     n_bond_atoms = len(conect[11:]) // 5
--> 213     if len(conect[11:]) % n_bond_atoms != 0:
    214         raise RuntimeError("Bond atoms aren't aligned proberly for CONECT "
    215                            "record: {}".format(conect))

ZeroDivisionError: integer division or modulo by zero

``` python
import MDAnalysis as mda

u = mda.Universe('4BXW.pdb')
```

**Comment by richardjgowers** [comment] 2016-08-20 13:23
This one is caused by a CONECT record which only lists one number (`CONECT 2727`), which as far as I understand means nothing?  So I guess a small check to make sure that CONECT lines with only one record get ignored?

**Comment by jbarnoud** [comment] 2016-08-24 14:03
Closed by #949

**Closed by jbarnoud** 2016-08-24 14:03 UTC
Labels: Component-Readers, Format-PDB
