### ISSUE TITLE
MDAnalysis.Writer exporting PDBs in bad format with bonds=True

### ISSUE THREAD

**Issue by icamps** [MDAnalysis/mdanalysis#3018] opened 2020-11-05 14:04 UTC
## Expected behavior ##

Save each frame trajectory as a PDB with the contact information separate by the `ENDMDL` after each PDB.

## Actual behavior ##

The `ENDMDL` directive is wrote BEFORE the `CONECT` session, breaking the structure of the PDB.

## Code to reproduce the behavior ##

Load a trajectory and export as with the `bonds=True , multiframe=True`. I am using:
complxx = u.select_atoms('segid PROT','segid LIG')
with MDAnalysis.Writer("output.pdb", bonds=True, multiframe=True) as W:
    for ts in u.trajectory:
        W.write(complxx)

## Current version of MDAnalysis ##

- Which version are you using? 2.0.0-dev0
- Which version of Python (`python -V`)? Python 3.8.6
- Which operating system? Ubuntu 20.04

**Comment by IAlibay** [comment] 2020-11-05 15:48
Thanks for reporting this @icamps 

What's troubling here too is that the behaviour exhibited is, I believe, nowhere near the PDB v3 standard.

As far as I can tell a 3 frame PDB should have the following structure (please do correct me if I'm wrong, pinging @RMeli spends much longer than me looking at the standard :) ):
```
MODEL
<ATOMS>
ENDMDL
MODEL
<ATOMS>
ENDMDL
MODEL
<ATOMS>
ENDMDL
<CONECT RECORD>
```

This way the CONECT record should only come once at the end of the multiframe PDB.

(looking at a very small selection of PDBs [2JUY, 6WPV], this seems to be the case).

If this is the correct interpretation, we should be applying `CONECT` in the same way we apply `END`, i.e. automatically on trajectory closing.

**Comment by IAlibay** [comment] 2020-11-05 15:59
Probably the limitation is if there is an expectation that the number of atoms changes across each models (which I don't think PDB was made for but I'm sure someone uses it that way), i.e. passing an updating atomgroup.

If we want to support that use case, I'm not sure what the intended behaviour should be 😕

**Comment by icamps** [comment] 2020-11-05 16:37
I am not aware about PDB standard, sorry.

@IAlibay , my feeling is that using only one  `CONECT`directive for a multiframe PDB is again the logic of the multiframe PDB in this case that the frames are obtained from a molecular dynamics simulation. The examples you got, are very different in their "born".

The idea I have in exporting each frame of a trajectory file as one PDB file, is that each of the records/models on the final PDB should behave like an independent PDBs concatenated, without any relationship among them (I mean, if I use any tool to extract them as separate individual PDBs).

In this case, the `ENDMDL` directive appears in each of the records always before the first `CONECT` directive, not at the final one.

**Comment by IAlibay** [comment] 2020-11-05 16:47
@icamps If I understand your use case correctly, the individual frames would vary in terms of number of atoms / bond topology?

I'm unfortunately not sure that this is what the PDB standard was made for (others can correct me / differ in opinions here, I do tend to be a standard purist).

If anything, MDAnalysis wouldn't be able to read the multiframe PDB back in as we don't support time-dependent changes in the number of atoms or bonds.

That being said maybe I'm completely missing something here, is there a standard for these kind of concatenated PDB model files?

**Comment by icamps** [comment] 2020-11-05 16:56
@IAlibay , nope. My use is as following:

1- done a molecular dynamics with fixed number of atoms,
2- export each time frame of the trajectory as a single PDB (so, all frames have the same number of atoms),
3- run analysis not available in MDAnalysis (using other software) in each PDB.

Within MDAnalysis, I didn't find how to export each frame as separate PDBs, just to a multiframe PDB.

Also, even thinking in the standard multiframe PDB as pointed out by you where only one `CONECT RECORD` appears at the end, this is not how the things are working now where each records have their own `CONECT RECORD `section.

**Comment by IAlibay** [comment] 2020-11-05 17:08
Thanks for the clarification @icamps !

I _think_ I get what you mean now, so each frame will be treated a single "PDB" of types by the other software?

Off the top of my head I'm not sure that the best approach here would be aside from writing lots of individual PDB files.

If the alternative software is another python tool, one of the alternatives here could be use a "file-like" object instead (similar to what we do in [propkatraj](https://github.com/Becksteinlab/propkatraj/blob/master/propkatraj/propkatraj.py)).

> Within MDAnalysis, I didn't find how to export each frame as separate PDBs, just to a multiframe PDB.

So doing this is essentially what you've been doing, but with the `with` and `for` statements reversed:

```python
u = mda.Universe(some-trajectory)

for i, ts in enumerate(u.trajectory):
    with mda.Writer(f'pdbfile_{i}.pdb', bonds='all') as W:  # bonds could also be 'conect' depend on what you need
        W.write(u.atoms)
```

> Also, even thinking in the standard multiframe PDB as pointed out by you where only one CONECT RECORD appears at the end, this is not how the things are working now where each records have their own CONECT RECORD section.

Completely agreed, apologies if it wasn't clear from my initial post, I 100% propose that we fix things to fit the PDB standard (as long as it doesn't break some other use case I'm not aware of).

**Comment by icamps** [comment] 2020-11-05 18:11
Thank you very much!

**Closed** 2020-11-20 18:05 UTC
Labels: Difficulty-easy, Format-PDB, defect
