### ISSUE TITLE
test_written_remarks_property test fails on ppc64le

### ISSUE THREAD

**Issue by junghans** [MDAnalysis/mdanalysis#2343] opened 2019-09-05 18:09 UTC
```
=================================== FAILURES ===================================
________________________ test_written_remarks_property _________________________
[gw7] linux -- Python 3.7.4 /usr/bin/python3
tmpdir = local('/tmp/pytest-of-mockbuild/pytest-0/popen-gw7/test_written_remarks_property0')
dcd = <MDAnalysis.lib.formats.libdcd.DCDFile object at 0x7fff600c7ad0>
    @given(remarks=strategies.text(
>       alphabet=string.printable, min_size=0,
        max_size=239))  # handle the printable ASCII strings
    @example(remarks='')
    def test_written_remarks_property(remarks, tmpdir, dcd):
formats/test_libdcd.py:320:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python3.7/site-packages/hypothesis/core.py:599: in execute
    % (test.__name__, text_repr[0])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <hypothesis.core.StateForActualGivenExecution object at 0x7fff4b696110>
message = "Hypothesis test_written_remarks_property(remarks=',', tmpdir=local('/tmp/pytest-of-mockbuild/pytest-0/popen-gw7/test_...d.DCDFile at 0x7fff600c7ad0>) produces unreliable results: Falsified on the first call but did not on a subsequent one"
    def __flaky(self, message):
        if len(self.falsifying_examples) <= 1:
>           raise Flaky(message)
E           hypothesis.errors.Flaky: Hypothesis test_written_remarks_property(remarks=',', tmpdir=local('/tmp/pytest-of-mockbuild/pytest-0/popen-gw7/test_written_remarks_property0'), dcd=<MDAnalysis.lib.formats.libdcd.DCDFile at 0x7fff600c7ad0>) produces unreliable results: Falsified on the first call but did not on a subsequent one
/usr/lib/python3.7/site-packages/hypothesis/core.py:769: Flaky
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_written_remarks_property(remarks=',', tmpdir=local('/tmp/pytest-of-mockbuild/pytest-0/popen-gw7/test_written_remarks_property0'), dcd=<MDAnalysis.lib.formats.libdcd.DCDFile at 0x7fff600c7ad0>)
```

Details [here](https://github.com/MDAnalysis/mdanalysis/files/3580662/build_ppc64le.txt)

**Comment by orbeckst** [comment] 2019-09-07 00:21
@junghans in the full log I find
```
E           hypothesis.errors.Flaky: Hypothesis test_written_remarks_property(remarks=',', tmpdir=local('/tmp/pytest-of-mockbuild/pytest-0/popen-gw7/test_written_remarks_property0'), dcd=<MDAnalysis.lib.formats.libdcd.DCDFile at 0x7fff600c7ad0>) produces unreliable results: Falsified on the first call but did not on a subsequent one
/usr/lib/python3.7/site-packages/hypothesis/core.py:769: Flaky
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_written_remarks_property(remarks=',', tmpdir=local('/tmp/pytest-of-mockbuild/pytest-0/popen-gw7/test_written_remarks_property0'), dcd=<MDAnalysis.lib.formats.libdcd.DCDFile at 0x7fff600c7ad0>)
Unreliable test timings! On an initial run, this test took 326.74ms, which exceeded the deadline of 200.00ms, but on a subsequent run it took 18.78 ms, which did not. If you expect this sort of variability in your test timings, consider turning deadlines off for this test by setting deadline=None.
```
which seems to say that the reason for the failure was a test run that took too long, not necessarily an erroneous result.

Is this failure reproducible on your end?

**Comment by tylerjereddy** [comment] 2019-09-07 01:28
I have access to that platform / hardware through the gcc compile farm (other MDA maintainers should be able to apply for accounts there if they want), though it will likely be some time before I can get to this.

We could add that hardware to our CI as well, although there wasn't much enthusiasm on my previous PRs to expand testing in similar ways (i.e., armv8). For ppc64le we'd need to be using travis.org in stead of .com because it is a beta feature & strange reasons...

**Comment by junghans** [comment] 2019-09-09 16:13
@orbeckst it is reproducible and same issue on aarch64. Details [here](https://github.com/MDAnalysis/mdanalysis/files/3591529/build_aarch64.txt)

**Comment by junghans** [comment] 2019-09-11 22:07
I just brought MDAnalysis back into Fedora: https://bodhi.fedoraproject.org/updates/FEDORA-2019-0ce3bfdc1d, but I excluded ppc64le and aarch64 for now, but looking forward to bring it back as soon as possible.

**Comment by IAlibay** [comment] 2022-01-19 01:38
@junghans - > 2 years late, but ppc64le and aarch64 is now regularly tested on the `develop` branch of MDAnalysis. Not sure what the status is re: Fedora but it may be worth seeing if those builds can be added back if there's interest?

Unless there's any objections I'll close this issue in the next few days.

**Comment by junghans** [comment] 2022-01-19 01:53
Mdanalysis got dropped from Fedora, so this can be closed!

**Comment by IAlibay** [comment] 2022-01-19 02:03
Sorry to hear that :(

**Closed by IAlibay** 2022-01-19 02:03 UTC
Labels: Component-Writers, close?
