### ISSUE TITLE
CYZONE selection failure in 0.13

### ISSUE THREAD

**Issue by Balasubra** [MDAnalysis/mdanalysis#715] opened 2016-02-12 09:30 UTC
This issue is regarding the failure of CYZONE in version 0.13.0 (https://groups.google.com/forum/#!topic/mdnalysis-discussion/x2vWhu4VfYQ). Probably the problem may also exist with CYLAYER, but i have not checked it.

The following code failed to generate the selection with v.0.13.0 but worked well with v.0.12.0
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PRMncdf,TRJncdf
U  = mda.Universe(PRMncdf,TRJncdf)
sel= U.select_atoms( "(resname WAT and name O) and cyzone 8 5 -5 name CA" )
if sel: print 'success'

**Comment by kain88-de** [comment] 2016-02-12 10:42
duplicate of #710, solution is proposed in #711

**Closed by kain88-de** 2016-02-12 10:42 UTC

**Comment by Balasubra** [comment] 2016-02-12 12:06
I am not getting something, I see that in #711, there is a solution/fix given for test_atomselections.py script. The error actually appeared in "MDAnalysis/core/Selection.py" .

**Comment by jbarnoud** [comment] 2016-02-12 12:09
`MDAnalysys/core/Selection.py` is modified by #711 as you can see in [the "File changed" tab of the pull request](https://github.com/MDAnalysis/mdanalysis/pull/711/files).

**Comment by kain88-de** [comment] 2016-02-12 12:11
the changes in `test_atomselections.py` are adding a unit-test to make sure this error doesn't show up in the future again.

**Comment by Balasubra** [comment] 2016-02-12 14:12
Thanks, by the way while reading the **"density_from_Universe"** code again, i found another issue
in line 518 (**density.py**)
grid /= float(n_frames)

If the user chooses trajectory indexing (start,stop), doing average as grid /= float(n_frames) will be wrong. Do i raise a new issue or pull ?

**Comment by kain88-de** [comment] 2016-02-12 14:45
please open a new issue with code that reproduces the problem
