### ISSUE TITLE
v1.0.0: rpm build fails on fedora rawhide

### ISSUE THREAD

**Issue by junghans** [MDAnalysis/mdanalysis#3056] opened 2020-12-04 15:57 UTC
From https://koji.fedoraproject.org/koji/taskinfo?taskID=56777342

I think the error is:
```
__init__.py:126: in <module>
    matplotlib.use('agg', warn=False)
E   TypeError: use() got an unexpected keyword argument 'warn'
___________ ERROR collecting MDAnalysisTests/analysis/test_align.py ____________
```

This is with python3-numpy-1.19.4-1.fc34, do we need a newer version on fedora?

Build log [here](https://github.com/MDAnalysis/mdanalysis/files/5643760/build.txt)

**Comment by IAlibay** [comment] 2020-12-04 16:03
@junghans this seems to be related to #2938 

The current solution is to pin to an older version of matplotlib, but we are hoping to release a 1.0.1 version very soon that should fix this (I think our own hurdle left is to re-enable CI since we've just migrated away from Travis).

**Comment by RMeli** [comment] 2020-12-04 16:06
Hi @junghans , unfortunately this is a known issue:  #2938

It should be fixed for release `1.0.1`. For the time being, the workaround is to pin the version of `matplotlib` to `<3.3`.

**Comment by junghans** [comment] 2020-12-04 16:15
Ok, I will patch #2763 into the rpm.

**Comment by junghans** [comment] 2020-12-04 16:25
Now it fails with a different error (see https://koji.fedoraproject.org/koji/taskinfo?taskID=56779633):
```
INTERNALERROR> AssertionError: ('MDAnalysisTests/analysis/test_data.py::test_all_exports', <WorkerController gw1>)
INTERNALERROR> assert not 'MDAnalysisTests/analysis/test_data.py::test_all_exports'
```

Build log [here](https://github.com/MDAnalysis/mdanalysis/files/5643962/build.txt)

**Comment by IAlibay** [comment] 2020-12-04 16:34
😕 I'm not sure we've properly tested with 3.9 (@jbarnoud I think did?), any reason it's rc1 and not the full release?

hopefully @orbeckst might have a better handle on if this is in any related to #2763

**Comment by junghans** [comment] 2020-12-04 16:43
It is rc1 of 3.9.1.

**Comment by junghans** [comment] 2020-12-04 16:53
F33 has 3.9.0, let's test that: https://koji.fedoraproject.org/koji/taskinfo?taskID=56781133

**Comment by junghans** [comment] 2020-12-04 17:03
Error stays the same:
```
INTERNALERROR> AssertionError: ('MDAnalysisTests/analysis/test_data.py::test_all_exports', <WorkerController gw39>)
INTERNALERROR> assert not 'MDAnalysisTests/analysis/test_data.py::test_all_exports'
```

End of build log [here](https://github.com/MDAnalysis/mdanalysis/files/5644187/build.txt)

**Comment by lilyminium** [comment] 2020-12-04 21:39
I can't reproduce on the current version of ``develop`` in 3.9.0 with numpy 1.19.4 (osx, clang). @junghans are you using the 1.0 release or the development package? Although I can't actually install the 1.0.0 mdanalysistests package on 3.9. It's a weird error because that particular test just checks that all files in `mdanalysistests.data.filenames` that should be in `__all__`, are. Maybe it's related to #2939?

**Comment by junghans** [comment] 2020-12-05 00:17
This was the 1.0.0 tarball, I can make a dockerfile to reproduce this.

**Comment by junghans** [comment] 2020-12-05 00:34
Here it is:
```Dockerfile
Dockerfile
FROM registry.fedoraproject.org/fedora:rawhide
RUN dnf -y install fedpkg
RUN git clone -b v1.0.0 https://src.fedoraproject.org/forks/junghans/rpms/python-MDAnalysis.git
WORKDIR python-MDAnalysis
RUN dnf -y builddep python-MDAnalysis.spec
RUN spectool -g python-MDAnalysis.spec
RUN fedpkg --release f34 local
```

**Comment by junghans** [comment] 2020-12-06 19:09
Now https://bugzilla.redhat.com/show_bug.cgi?id=1903956

**Comment by IAlibay** [comment] 2021-11-18 20:56
@junghans sorry we kinda lapsed on looking into this - is this still an active issue?

**Comment by junghans** [comment] 2021-11-19 00:19
We dropped the mdanalysis package from Fedora, so I guess yes, but it also doesn't matter anymore.

**Closed** 2021-11-19 00:19 UTC
Labels: installation, downstream
