### ISSUE TITLE
Running encores with multiple cores

### ISSUE THREAD

**Issue by kmorisa** [MDAnalysis/mdanalysis#4538] opened 2024-03-28 14:07 UTC
Good morning,

I would like to know if there is anything wrong with:
ces0, details0 = encore.similarity.ces(list(data.values()), ncores=8)
because my dashboard seems to show that only one cpu has been used for the calculation.
I have 32 cpus available.

Thank you.

**Comment by orbeckst** [comment] 2024-03-29 18:54
This seems to be a duplicate of https://github.com/MDAnalysis/mdaencore/issues/64 so I am closing it.  

Note that ENCORE was moved to its own MDAKit and we will remove it from MDAnalysis itself soon. Thus we are encouraging any discussions/issue to be at https://github.com/MDAnalysis/mdaencore/

**Closed as completed by orbeckst** 2024-03-29 18:54 UTC

**Comment by orbeckst** [comment] 2024-03-29 19:00
@kmorisa please go to https://github.com/MDAnalysis/mdaencore/issues/64 and hopefully the ENCORE maintainers can contribute to the discussion and find a solution.

**Comment by kmorisa** [comment] 2024-03-29 19:02
Yes, that is exactly what I am experiencing.
Thank you for your guidance.

**Comment by orbeckst** [comment] 2024-03-30 03:42
As detailed in the referenced issue, parallelization is only about different parameters and not per ensemble. Thus, the reported behavior is normal.

**Comment by kmorisa** [comment] 2024-03-30 13:55
Thank you for letting me know, and I understand!
