### ISSUE TITLE
Make other properties time dependent (e.g. charges)

### ISSUE THREAD

**Issue by pstaerk** [MDAnalysis/mdanalysis#3504] opened 2022-01-17 09:04 UTC
## Is your feature request related to a problem? ##
My group is very interested in having the ability to make the charges time dependent.
We are simulating fluctuating electrodes (in LAMMPS), where the charge is treated as an additional degree of freedom.
Lammps trajectories enable you to output custom styles where e.g. the charge is also written for each timestep and to my limited knowledge this is possible in other simulation frameworks too.

## Describe the solution you'd like ##
Ideally, the trajectory parser should be able to accept custom style descriptions (or guess them from the `lammpstrj` dump file's header) and then make the charge a part of the trajectory's attributes.
From looking at the parser's code this should not be too hard to add, but I am not sure how the hard change to the topology/trajectory backend would be.

**Comment by hmacdope** [comment] 2022-01-17 10:41
The `ts.data` attribute can be used to hold arbitrary timestep associated data. You could always add the charges to that IMO.

 See [this line](https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/coordinates/LAMMPS.py#L553) for an example of adding to it in the LAMMPS parser. :)

**Comment by pstaerk** [comment] 2022-01-17 14:16
Thanks for this very helpful answer! :)

**Comment by pstaerk** [comment] 2022-01-17 14:24
Is this something which could be included in MDAnalysis permanently? I have the impression that a number of people could use such a time-dependent charge reader (or a bit more flexibility in time dependent quantities).

**Comment by IAlibay** [comment] 2022-01-17 15:01
So as you alluded to @pstaerk part of the issue is that our topology & trajectory framework really was built on the idea of "early generation" force fields where topology attributes like partial charge are static and the only things that change are the positions/forces/velocities.

Adding more attributes to the trajectory technically is possible, but would involve a lot of re-work, and as things currently stand would possibly lead to increased access costs to these topology attributes (or at the very least there's a computational cost associated with reading an array of data out of the timestep object). This is probably going to be problematic in the majority use case where time-dependent topology attributes isn't a thing that is really supported (I guess technically AMBER and GROMACS support AMEOBA and DRUDE respectively, but I'm not sure we can even deal with them properly at the moment).

@hmacdope's solution would be the simplest one, and adding the ability to read into `ts.data` if available would be a reasonable addition to the reader. **I would likely support a PR that implemented this. Would you or anyone from your group be interested in contributing this?** However, I can also see how this might be not so user-friendly / easily to deal with (as you would have two charge attributes, one in `ts.data` and one that is static in `atoms.charges`).

Allowing topology attributes to iterate is something that in the short term is probably not going to be very feasible in the short term I _think_, but I'll let @lilyminium add her thoughts here since she's more knowledgeable on recent changes to that part of the code.

**Comment by hmacdope** [comment] 2022-01-17 21:44
> Is this something which could be included in MDAnalysis permanently? I have the impression that a number of people could use such a time-dependent charge reader (or a bit more flexibility in time dependent quantities).


I would support a PR with this functionality, as we are generally trying to improve the flexibility of the LAMMPS parsers. :)

**Comment by hmacdope** [comment] 2022-01-17 22:11
I should also mention in advance that I think the best way to do this is to support the general case, ie reading any additional column. 

You can then specify additional columns as an argument to the reader.

**Comment by orbeckst** [comment] 2022-02-20 18:46
If we have a trajectory reader that stores arbitrary data in the `ts.data` dict under a certain key, can we write custom attributes that look into `ts.data[KEY][atom.ix]`? Maybe it's not as performant as the native topology framework but it would provide a flexible path to time-dependent data and it also remains true to the original spirit of #363 to lookup data in individual attribute arrays. 

cc @richardjgowers @lilyminium

**Comment by hejamu** [comment] 2024-03-04 20:25
Fixed by #3608, @hmacdope @orbeckst ?

**Comment by hmacdope** [comment] 2024-03-04 20:28
I believe so!

**Closed as completed by hmacdope** 2024-03-04 20:28 UTC
Labels: enhancement, Component-Readers, Component-Core, Difficulty-hard, Component-Topology, format-LAMMPS
