### ISSUE TITLE
Problem in RDF calculation: Atomgroups read as one

### ISSUE THREAD

**Issue by HemanthHaridas** [MDAnalysis/mdanalysis#2168] opened 2019-01-01 06:31 UTC
If you have a **QUESTION** such as 

- how to use MDAnalysis in general
- how to accomplish something specific,
- what output means
- ... or similar questions related to USING MDAnalysis 

then please *ask this question on the user mailing list*

   https://groups.google.com/forum/#!forum/mdnalysis-discussion

The issue tracker is meant for DEFECTS ("BUGS"), new FEATURES, and decisions on the API. In order to keep the volume of work on the issue tracker manageable for our volunteer developers, we will IMMEDIATELY CLOSE ISSUES THAT ARE BETTER ANSWERED ON THE USER MAILINGLIST.

We really appreciate you as a user getting in touch with us --- no matter what you want to discuss. But we need your help keeping the amount of work manageable so please use the mailing list for questions and the issue tracker for code-related issues.

Thank you!

The MDAnalysis Development Team

**Comment by HemanthHaridas** [comment] 2019-01-01 06:32
Sir,

I tried using the above code, to generate an RDF for a system of 21 Adenine molecules distributed over a graphene sheet. But I'm getting an RDF profile where the 21 Adenine bases are counted as one, whereas I need the RDF profile with respect to the centre of mass of each Adenine residue. The PSF file contains the residue id's and bond information of all the 21 residues. Kindly help me with this issue.
![adenine-4](https://user-images.githubusercontent.com/44941237/50570736-6ae64780-0dbc-11e9-8599-151e4bb7a2bb.png)
Attached is the plot that i got from MDAnalysis.

**Comment by orbeckst** [comment] 2019-01-07 22:31
Is this question related to https://groups.google.com/d/msg/mdnalysis-discussion/CgMT-3JuiRk/1062cloECQAJ ?

**Comment by orbeckst** [comment] 2019-01-07 22:36
This issue appears to be a question, not a bug report and therefore I am closing it. Can you please post your question to the user list? 

Please include a description of what you want to achieve (eg what do you mean by
>  generate an RDF for a system of 21 Adenine molecules distributed over a graphene sheet

It helps when you write down the mathematical definitions of the quantities that you want to calculate.

**Closed by orbeckst** 2019-01-07 22:36 UTC

**Comment by HemanthHaridas** [comment] 2019-01-08 02:56
Yes,it is.
