### ISSUE TITLE
No module named duecredit

### ISSUE THREAD

**Issue by Ash1000** [MDAnalysis/mdanalysis#1925] opened 2018-05-31 06:15 UTC
Hi everyone, I am unable to successfully run MDAnalysis. I was informed last time, that the following issue will be fixed in coming release. I apologize for asking here, but would someone like to inform me that when the updated MDAnalaysis version is expected to release?

/home/ash/.local/lib/python2.7/site-packages/MDAnalysis/due.py:88: UserWarning: No module named duecredit
  warnings.warn(str(err))

**Comment by kain88-de** [comment] 2018-05-31 09:15
This is only a warning and you should still be able to use MDAnalysis. Yes the warning is annoying but again you should still be able to use MDAnalysis normally.

**Comment by orbeckst** [comment] 2018-05-31 19:14
And if you don't want to see the warning, install duecredit:
```
pip install duecredit
```

Closed as duplicate of #1872

**Comment by orbeckst** [comment] 2018-05-31 19:16
>  I am unable to successfully run MDAnalysis

Just to double check: What other indications (besides the duecredit warning) do you have that MDAnalysis is not working properly?

Did you [run the tests](https://github.com/MDAnalysis/mdanalysis/wiki/UnitTests#users)?

**Comment by orbeckst** [comment] 2018-06-07 16:57
No more information, closing.

**Closed by orbeckst** 2018-06-07 16:57 UTC
