### ISSUE TITLE
The Universe.dimensions is not assigned properly when loading tpr file

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#1834] opened 2018-03-15 11:50 UTC
I'm interested in reading the box information from tpr file, but it seems that the box information is assigned correctly.
I have checked the tpr file using the `gmx dump` and the box information is included in the tpr file under the box keyword.
```
...
box (3x3):
   box[    0]={ 3.50600e+00,  0.00000e+00,  0.00000e+00}
   box[    1]={ 0.00000e+00,  3.40400e+00,  0.00000e+00}
   box[    2]={ 0.00000e+00,  0.00000e+00,  3.89900e+00}
...
```
### Expected behaviour
```python
import MDAnalysis as mda
u = mda.Universe(tprfile)
dim = u.dimensions
```

### Actual behaviour
```
Traceback (most recent call last):
  File "~/mdanalysis/package/MDAnalysis/core/universe.py", line 447, in __getattr__
    segment = self._instant_selectors[key]
KeyError: 'dimensions'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "~/anaconda3/envs/py36_intel/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-23f7dbb5070a>", line 1, in <module>
    u.dimensions
  File "~/mdanalysis/package/MDAnalysis/core/universe.py", line 449, in __getattr__
    raise AttributeError('No attribute "{}".'.format(key))
AttributeError: No attribute "dimensions".
```

### Currently version of MDAnalysis:
mda0.17.0/py36

**Comment by kain88-de** [comment] 2018-03-15 12:41
I think this is because a box is part of the trajectory for mdanalysis and with only a tpr there is no TimeStep object to access the dimension keyword. I'm not sure if this is easily fixable.

ping @richardjgowers

**Comment by xiki-tempula** [comment] 2018-03-15 13:44
@kain88-de Thank you for the comment. I wonder why cannot the tpr file be loaded as a one frame timestep as a gro file with charge and a couple of other things? 
It seems to me that the tpr file has the positions (stored under the field of x) and velocities under the field of v.

**Comment by kain88-de** [comment] 2018-03-15 13:50
I'm not sure if there is a technical reason why we never did this.
The others might know more

**Comment by richardjgowers** [comment] 2018-03-15 14:47
Hello @xiki-tempula 

So dimensions is part of the coordinates side of things, things from topology don't change over time, whilst coordintaes (and maybe box size) do.  You're right that we should be able to read a single frame of coordinates from a tpr file, there's currently issue #464 for this, which would include dimensions information too.  I'm closing this as a duplicate of that.

**Closed by richardjgowers** 2018-03-15 14:47 UTC
Labels: Component-Readers, Format-Gromacs
