### ISSUE TITLE
Pip Install Crashing on Clang 

### ISSUE THREAD

**Issue by dldereklee** [MDAnalysis/mdanalysis#3381] opened 2021-08-02 20:10 UTC
## Expected behavior ##

pip install works

## Actual behavior ##

pip install crashes with the following error output
```
MDAnalysis/lib/_cutil.cpp:716:34: note: expanded from macro '__Pyx_sst_abs'
        #define __Pyx_sst_abs(value) std::abs(value)
                                     ^
    MDAnalysis/lib/_cutil.cpp:25992:20: note: use function 'std::abs' instead
    MDAnalysis/lib/_cutil.cpp:716:34: note: expanded from macro '__Pyx_sst_abs'
        #define __Pyx_sst_abs(value) std::abs(value)
                                     ^
    MDAnalysis/lib/_cutil.cpp:25992:20: note: include the header <cstdlib> or explicitly provide a declaration for 'std::abs'
    MDAnalysis/lib/_cutil.cpp:716:34: note: expanded from macro '__Pyx_sst_abs'
        #define __Pyx_sst_abs(value) std::abs(value)
                                     ^
    MDAnalysis/lib/_cutil.cpp:29420:16: warning: absolute value function 'abs' given an argument of type 'const Py_ssize_t' (aka 'const long') but has parameter of type 'int' which may cause truncation of value [-Wabsolute-value]
        if (likely(__Pyx_sst_abs(size) <= 1)) {
                   ^
    MDAnalysis/lib/_cutil.cpp:716:34: note: expanded from macro '__Pyx_sst_abs'
        #define __Pyx_sst_abs(value) std::abs(value)
                                     ^
    MDAnalysis/lib/_cutil.cpp:29420:16: note: use function 'std::abs' instead
    MDAnalysis/lib/_cutil.cpp:716:34: note: expanded from macro '__Pyx_sst_abs'
        #define __Pyx_sst_abs(value) std::abs(value)
                                     ^
    MDAnalysis/lib/_cutil.cpp:29420:16: note: include the header <cstdlib> or explicitly provide a declaration for 'std::abs'
    MDAnalysis/lib/_cutil.cpp:716:34: note: expanded from macro '__Pyx_sst_abs'
        #define __Pyx_sst_abs(value) std::abs(value)
                                     ^
    223 warnings and 13 errors generated.
    error: command 'clang' failed with exit status 1
```

## Code to reproduce the behavior ##

`pip install --upgrade MDAnalysis  `

## Current version of MDAnalysis ##

- Which version of Python (`python -V`)?  Python 3.8.9 (using pyenv)
- Which operating system? Mac OS Catalina
- Apple clang version 12.0.0 (clang-1200.0.32.21)

**Comment by lilyminium** [comment] 2021-08-02 20:46
Hmm, I can't reproduce this on Python 3.8.9 with MacOS Catalina, clang 6.0.0. Could you please paste errors from the output (it'll say `error:` for those)?

**Comment by dldereklee** [comment] 2021-08-02 20:51
```
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:320:9: error: no member named 'isinf' in the global namespace
  using ::isinf;
        ~~^
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:321:9: error: no member named 'isnan' in the global namespace
  using ::isnan;
        ~~^
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isnormal' in the global namespace
  using ::isnormal;
        ~~^
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:323:7: error: no member named 'isgreater' in the global namespace; did you mean '::std::greater'?
  using ::isgreater;
        ^~
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:325:9: error: no member named 'isless' in the global namespace
  using ::isless;
        ~~^
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'islessequal' in the global namespace
  using ::islessequal;
        ~~^
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:327:9: error: no member named 'islessgreater' in the global namespace
  using ::islessgreater;
        ~~^
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:328:9: error: no member named 'isunordered' in the global namespace
  using ::isunordered;
        ~~^
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
  using ::isunordered;
```

**Comment by hmacdope** [comment] 2021-08-03 02:00
seems like your `stdlib` is not being picked up properly. How did you install clang? With XCode or with something like brew? Or something else.

**Comment by hmacdope** [comment] 2021-08-03 23:42
Would you be able to try a version of clang installed with `brew` ? something like:


`brew install llvm` followed by

`export CC=/path/to/brew/clang/bin/clang` and `export CXX=/path/to/brew/clang/bin/clang++`

 the brew path for clang is **often** `/usr/local/opt/llvm` making the above command `CXX=/usr/local/opt/llvm/bin/clang++` although you will need to check the exact path.

**Comment by orbeckst** [comment] 2021-08-21 19:21
@dldereklee did you try @hmacdope 's suggestion? 

When we cannot reproduce an error in our tests in the CI or on local machines then the only way we can make any progress is by users working with us.

If there's no additional activity on this issue we will eventually close it as stale.

**Comment by dldereklee** [comment] 2021-08-23 17:22
I ended up just running the tool through Docker instead. I tried @hmacdope's suggestion, but I still get the same error.

**Comment by hmacdope** [comment] 2021-08-24 23:37
Thanks @dldereklee, I am unable to reproduce your problem myself but am glad that you managed to find a workaround. I will close this now but feel free to re-open if anything pops up.

**Closed by hmacdope** 2021-08-24 23:37 UTC
Labels: OpSys-OSX, installation, more information needed
