### ISSUE TITLE
test_util Failed

### ISSUE THREAD

**Issue by xiki-tempula** [MDAnalysis/mdanalysis#2171] opened 2019-01-10 14:35 UTC
**Expected behavior**
The test_util should run smoothly in travis. However, things happen. I think this is probably a pytest issue.

https://travis-ci.org/MDAnalysis/mdanalysis/jobs/477798878

**Actual behavior**

```python
____________ TestWarnIfNotUnique.test_warn_if_not_unique_once_outer ____________
Fixture "warn_msg" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
__________ TestWarnIfNotUnique.test_warned_state_restored_on_failure ___________
Fixture "warn_msg" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
____________ TestWarnIfNotUnique.test_warn_if_not_unique_once_inner ____________
Fixture "warn_msg" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
_______ TestWarnIfNotUnique.test_warn_if_not_unique_multiple_references ________
Fixture "warn_msg" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
_____________ TestWarnIfNotUnique.test_warn_if_not_unique_unnamed ______________
Fixture "warn_msg" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
```

**Code to reproduce the behavior**

testsuite/MDAnalysisTests/lib/test_util.py

**Comment by richardjgowers** [comment] 2019-01-10 15:00
duplicate of #2172

**Closed by richardjgowers** 2019-01-10 15:00 UTC
