### ISSUE TITLE
unique segments aren't unique?

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1108] opened 2016-12-05 10:07 UTC
### Expected behaviour

I've looked at [1nmu](http://www.rcsb.org/pdb/explore/explore.do?structureId=1NMU) which has 4 unique chains A, B, C, D. When I do `u.atoms.segments.unique.segids` I would expect only to see 4 entries. 

### Actual behaviour

I see 8. `A, B, C, D, A ,B, C, D`. The segments are doubled. That might be because of the formating for the PDB

```
ATOM .... D
TER ....   D 
HETATM ... # here it starts from chain A again.
```

It might just be me being ignorant of how PDB's and the HETATM entries work but I find this a bit surprising. 

### Code to reproduce the behaviour

``` python
import MDAnalysis as mda

u = mda.Universe('1nmu.pdb')
u.atoms.segments.unique.segids
....

```

### Currently version of MDAnalysis:
(run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
0.16.0dev0

**Comment by richardjgowers** [comment] 2016-12-05 10:13
This is working as intended ([A, B, C, D, A, B, C, D] leads to 8 segments), but I don't actually know how segments and pdbs *should* work.  So is this meant to get condensed to 4 segments?

**Comment by kain88-de** [comment] 2016-12-05 10:17
I was surprised to see segments with the same name again in the unique list.  From the pdb entry I would have thought that only 4 are in the PDB.  It actually reduces to 4 if I to `u.select_atoms('protein')`. So this might just be hetatom handling that I'm unfamiliar with.

**Comment by kain88-de** [comment] 2016-12-05 10:49
@orbeckst Do you have anymore wisdom to share on PDB topologies?

**Comment by orbeckst** [comment] 2016-12-05 17:32
I think all 'A' chains are supposed to get merged, etc. The HETATM section ("Non-polymer or other “non-standard” chemical coordinates, such as water molecules or atoms presented in HET groups use the HETATM record type.") comes after ATOM records.

* [HET](http://www.wwpdb.org/documentation/file-format-content/format33/sect4.html) records have a *ChainID*, which implies that these are molecules associated with amino or nucleic acid polypeptides
* [HETATM](http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#HETATM) appear to come after ATOM records but I haven't found the place where this is stated explicitly.

**Comment by richardjgowers** [comment] 2016-12-06 11:03
So from looking at the files, I think there's 4 chains in the ATOM section, and then HETATM stuff.  In the PDB file the HETATM stuff gets the chainID of one of the original 4 chains, whereas in the mmtf file the HETATM stuff gets its own `chain_id`, but then also a `chain_name` which corresponds to the chainID given in the pdb file.

```python
In [10]: import mmtf

In [11]: top = mmtf.fetch('1nmu')

In [12]: top
Out[12]: <mmtf.api.mmtf_reader.MMTFDecoder at 0x7f17efaf7d10>

In [13]: top.chain_name_list
Out[13]: [u'A', u'B', u'C', u'D', u'A', u'C', u'A', u'B', u'C', u'D']

In [14]: top.chain_id_list
Out[14]: [u'A', u'B', u'C', u'D', u'E', u'F', u'G', u'H', u'I', u'J']


```

I'm not sure if which of these is the best to use, either way #1109 should get fixed so that both these fields are read and saved to the segment objects. (`chainID` and `chain_name` attributes?)

**Comment by kain88-de** [comment] 2017-01-02 21:10
@richardjgowers 'chain_name_list` is the correct thing here as this corresponds to the old chain identifiers in the PDB

**Comment by kain88-de** [comment] 2017-01-02 21:14
So the unique behavior here is definitely wrong. There exist only 4 chains and the HEATOMS shouldn't be a separate chain when I chose the unique segments. How are the unique segments build right now?

**Comment by richardjgowers** [comment] 2017-01-03 09:41
So currently we're getting the number of chains directly from the `MMTFDecoder` object

```python
In [2]: top = mmtf.fetch('1nmu')

In [3]: top.num_chains
Out[3]: 10
```

So the MMTFParser isn't actually deciding anything about what the chains are, it's just following what the mmtf module says.

**Comment by kain88-de** [comment] 2017-01-03 09:43
@richardjgowers the problem also exists with the PDB parser. The same Chain identifier get's shown twice when I ask for unique segments.

**Comment by richardjgowers** [comment] 2017-01-03 09:46
Ok in PDBParser any change in segid/chainID gets called a new segment, so `A B A` is 3 chains not 2.  I can change this to group segids together, but then it would work differently to the MMTFParser

**Comment by kain88-de** [comment] 2017-01-03 09:58
So then when do we generally define a segment as unique? How would it work in other topologies

**Comment by richardjgowers** [comment] 2017-01-03 10:03
Each individual Parser decides on what segments are.  Once the segment information leaves the Parser it's not processed any further.

**Comment by kain88-de** [comment] 2017-01-03 10:05
Then how should I understand the unique identifier? When would the normal segments contain more elements then unique.segments.  (Maybe the problem is that I'm just confused by the behavior of unique)

**Comment by richardjgowers** [comment] 2017-01-03 10:17
Do you mean the `.unique` method? That's just like calling `set(atoms.segments)` but it returns itself as a Group still. So.

```python
u = mda.Universe()

seggroup = u.segments[0] + u.segments[1] + u.segments[0]

seggroup.unique  # returns u.segments[0] + u.segments[1]

# and by definition
u.segments.unique == u.segments
```

So the parser defines what Segments exist in the Universe, this doesn't change unless you explicitly add/remove Segments.  `SegmentGroup.unique` then returns the unique Segments, as defined according to the Parser when the Universe was created.

https://github.com/MDAnalysis/mdanalysis/blob/develop/package/MDAnalysis/core/groups.py#L1717

I think you're overthinking what `.unique` does.

The problem here is that `MMTFDecoder` is saying there's 10 chains and I've directly translated that into 10 segments in the Parser

**Comment by kain88-de** [comment] 2017-01-03 11:12
> I think you're overthinking what .unique does.

Yeah likely. But that's easy with the unique doc string and the way segments are represented in the REPL.  Since the REPL uses the CHAINID that was given in the PDB to represent a segment my intuition was that same CHAINID means same segment. But that was false. The actual PDB is a bit more complicated.  

There are two things I draw from the discussion. 

1. The `repr` function doesn't return an  optimal value that clearly shows MDAnalysis is treating two segments with the same CHAINID as truly separate.
2. The `unique` docs should specify what unique means. @richardjgowers example in https://github.com/MDAnalysis/mdanalysis/issues/1108#issuecomment-270084258 would fit good there.

**Closed** 2017-04-04 11:31 UTC
Labels: Component-Topology, Format-PDB
