### ISSUE TITLE
segments object isn't properly documented.

### ISSUE THREAD

**Issue by kain88-de** [MDAnalysis/mdanalysis#1105] opened 2016-12-04 14:50 UTC
We need docs for how segments work see  https://github.com/MDAnalysis/mdanalysis/issues/1105#issuecomment-264824341

# Original Issue

I right now have the problem that I want to convert a selection of `bynum 1:34 or bynum 128:256 or ...` into selection I can actually transfer between different topologies.  The target should be something like `(chain A and resid 1 to 45) or (chain B and resid 1 to 128)`, *here for VMD*.

I know have a selection spanning several segments named *domain* 

 `'bynum 192:214 or bynum 229:405 or bynum 420:638 or bynum 830:852 or bynum 867:1043 or bynum 1058:1276'`

The crucial part here is that the selection spans several segments! My confusion is now that I think that accessing the segments and lower levels in that selection will **only** returns atoms in the selection and not from the rest of the topology

### Code to reproduce the behaviour

Here is a test case

``` python
import MDAnalysis as mda

u = mda.fetch_mmtf('1nmu')
# exclude all HETATM entries
protein = u.select_atoms('protein')
# make a selection across chains
sel = protein.select_atoms('(segid A and resid 10-50) or (segid C and resid 51-100)')
for seg in sel.segments:
    print(len(seg.residues.resids), seg.residues.resids[:10])
```

This prints that the resids are 368 long. That corresponds to all residues in the segment `A` or `C`. I would have expected that this would actually only contain 50 residues.

### Currently version of MDAnalysis:
0.16.0dev0

**Comment by kain88-de** [comment] 2016-12-04 15:10
This might also just have been that my PDB restarts ATOMID count several times.

**Comment by kain88-de** [comment] 2016-12-04 15:18
I also see strange things that an Atomgroup with 14 atoms but `ag.segments[0].residues` contains 410 residues. Seems to me that `segments[0]` does select the segment from the whole topology.

**Comment by kain88-de** [comment] 2016-12-04 15:34
A little helper
```python
def ranges(ar):
    """ find ranges of consecutive numbers """
    _ranges = []
    begin = ar[0]
    for el in np.where(np.diff(ar) != 1)[0]:
        end = ar[el]
        _ranges.append((begin, end))
        begin = ar[el + 1]
    _ranges.append((begin, ar[-1]))
    return _ranges
```

My first try to extract the chain ID and the corresponding residue id ranges for a given atomgroup. That one didn't work well. It would select the same ranges for atomgroups with containing a non overlapping set of atoms in a topology.

```python
def chain_ranges(ag):
    return {seg.segid: ranges(seg.resids) for seg in ag.segments}
```

This version worked in the end.  This version doesn't go down the levels in the topology. That is surprising I would have initially thought that the first version would also work.

```python
def chain_ranges(ag):
    segmentids = np.unique(ag.segids)
    res = {}
    for segid in segmentids:
        idx = np.where(ag.segids == segid)[0]
        res[segid] = ranges(ag.resids[idx])
    return res
```

**Comment by dotsdl** [comment] 2016-12-04 17:18
In addition to restarting ATOMID several times, does your PDB file restart RESID several times, too? Resids are not unique identifiers for the new topology system (they are a label, not really any different from resnames), so it looks to me like each segment has, e.g. a residue with resid `11`. Is this the case?

**Comment by kain88-de** [comment] 2016-12-04 19:14
I removed the ATOMID issue later on. And yes the RESID are restarted for every chain that isn't unusual though (that is why I treat the combination of CHAINID and RESID as a unique identifier). 

See here for an example PDB entry: [1NMU](http://www.rcsb.org/pdb/explore/explore.do?structureId=1NMU). This contains two chains with a where residues share the same RESID.

Anyway if I do `atoms.segments[0].residues` that I expect to only get the residues in segment 1. I see it as a way to do a selection with the python object itself. I was really surprised to see that the atom number was increased again when I got "down" in the structure.

**Comment by kain88-de** [comment] 2016-12-05 10:47
OK I now have a working example. I updated the first post accordingly

**Comment by richardjgowers** [comment] 2016-12-05 10:55
`.segments` works differently to how you're thinking.

```python

sel = select_atoms('something')

segment = sel.segments[0]  # selects the segment as an object

# segment at this point has no memory of sel, it just represents the segment

segments.residues  # just gives you all the residues, because there's no memory of where it came from

```

**Comment by kain88-de** [comment] 2016-12-05 11:01
Ok then how would I then programatically select the residues for each segment in a selection? My approach in the last function in https://github.com/MDAnalysis/mdanalysis/issues/1105#issuecomment-264710598 doesn't look that nice.

**Comment by richardjgowers** [comment] 2016-12-05 11:04
Does this work?

```python
for segid in sel.segments.segids:
    print sel.residues[sel.residues.segids == segid]
```

**Comment by kain88-de** [comment] 2016-12-05 12:00
yeah that would work but isn't much different from my own solution. It also feels awkward. If I wouldn't have a selection that only works on a part of a segment  but rather select one more more segments completely the naive version 

```python
for seg in sel.segments;
    print(sel.residues)
```

would work.

I'm OK with the workaround for me. But I would like to hear what others say. I would also add this to the docs/FAQ as a easy mistake that can be made.

**Comment by richardjgowers** [comment] 2016-12-05 13:13
Yeah definitely needs a warning/note somewhere as it's a potential gotcha.

If we had the set operations that are mentioned in #726 we could have something like

```python
for seg in sel.segments:
    res = seg.residues & sel.residues
    res = seg.residues.intersect(sel.residues)  # or maybe only as a method
```

**Comment by dotsdl** [comment] 2016-12-05 23:44
So since doing something like "from this `AtomGroup`/`ResidueGroup`/`SegmentGroup` get me an `AtomGroup`/`ResidueGroup`/`SegmentGroup` for each value of `topologyattr` present" can be a pretty common operation, and essentially amounts to a `groupby`, should we add a `groupby` method a la `pandas` and [`datreant`](https://github.com/datreant/datreant.core/blob/develop/src/datreant/core/agglimbs.py#L566) that does essentially this under the hood?

**Comment by dotsdl** [comment] 2016-12-06 00:51
Made a prototype of my suggestion in #1112.

**Comment by orbeckst** [comment] 2017-04-04 09:29
Add https://github.com/MDAnalysis/mdanalysis/issues/1268#issuecomment-291436447 (how to create new segments).

**Comment by orbeckst** [comment] 2017-05-10 01:14
More on "How to create segments" https://github.com/MDAnalysis/mdanalysis/issues/1268#issuecomment-291436447 : As described by @richardjgowers the following works:
```python
>>> import MDAnalysis as mda
>>> from MDAnalysisTests.datafiles import GRO

>>> u = mda.Universe(GRO)

>>> new_seg = u.add_Segment(segid='new')
>>> u.residues[:10].segments = new_seg
>>> print(u.segments)
<SegmentGroup [<Segment SYSTEM>, <Segment new>]>
>>> print(u.segments[1].atoms)
<AtomGroup [<Atom 1: N of type N of resname MET, resid 1 and segid new>, <Atom 2: H1 of type H of resname MET, resid 1 and segid new>, <Atom 3: H2 of type H of resname MET, resid 1 and segid new>, ..., <Atom 155: HA2 of type H of resname GLY, resid 10 and segid new>, <Atom 156: C of type C of resname GLY, resid 10 and segid new>, <Atom 157: O of type O of resname GLY, resid 10 and segid new>]>
```

However, if I do *not* use `new_seg` but instead `u.segments[0]` then it does *not* work:
```python
>>> u = mda.Universe(GRO)
>>> u.add_Segment(segid='new')
>>> print(u.segments)
<SegmentGroup [<Segment SYSTEM>, <Segment new>]>
>>> u.residues[:10].segment = u.segments[1]
>>> print(u.segments[1].atoms)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-76-8ce8f87cd7cb> in <module>()
----> 1 print(u.segments[1].atoms)
...
/Volumes/Data/oliver/Biop/Library/python/mdanalysis/package/MDAnalysis/core/topology.pyc in residues2atoms_1d(self, rix)
    263         """
    264         try:
--> 265             return np.concatenate([self._RA[r] for r in rix])
    266         except TypeError:  # integers aren't iterable, raises TypeError
    267             return self._RA[rix].copy()  # don't accidentally send a view!

ValueError: need at least one array to concatenate
```

Note that 
```python
>>> new_seg == u.segments[1]
True

>>> new_seg is u.segments[1]
False
```

I find this pretty confusing. Could @richardjgowers or @dotsdl explain what is going on and if this is expected behavior??

**Comment by richardjgowers** [comment] 2017-05-10 09:57
@orbeckst in the second block you assign to `ResidueGroup.segment` not `ResidueGroup.segments` (note the extra s).  So this just creates an attribute on the RG called 'segment' that does nothing. We need to use `.segments` because it might be that the residues have more than one segments (similarly an AtomGroup uses `.residues` rather than `.residue`), but I do agree that it doesn't read as well as `.segment`.

PR #1186 is designed to stop things like this happening by not allowed arbitrary attributes on Groups to be set.

I could look at adding `AtomGroup.residue` and `ResidueGroup.segment` as a property which only allows setting (not getting), which would then make the above code work.  Ie we can't query the residue of an AtomGroup, but we can assign all Atoms in a Group to a Residue.

The difference between `==` and `is` is working as intended, for example:

```python
In [12]: at1 = u.atoms[10]

In [13]: at2 = u.atoms[10]

In [14]: at1 == at2
Out[14]: True

In [15]: at1 is at2
Out[15]: False
```
Here `at1` and `at2` are both views/pointers to the same Atom, but aren't actually the same object themselves.  You can get similar behaviour with most python objects, eg integers:

```python
In [18]: a = 123456

In [19]: b = 123456

In [20]: a == b
Out[20]: True

In [21]: a is b
Out[21]: False
```

**Comment by richardjgowers** [comment] 2017-12-07 14:31
@kain88-de the following is now possible, does this fix the original issue here (selecting all residues belonging to certain segids)?

```python
In [18]: u = mda.fetch_mmtf('1nmu')

In [19]: protein = u.select_atoms('protein')

In [20]: protein.residues.groupby('segids')
Out[20]: 
{u'A': <ResidueGroup with 368 residues>,
 u'B': <ResidueGroup with 104 residues>,
 u'C': <ResidueGroup with 368 residues>,
 u'D': <ResidueGroup with 103 residues>}
```

**Comment by kain88-de** [comment] 2017-12-07 15:24
the groupby does work

**Comment by richardjgowers** [comment] 2020-06-06 12:52
I think hopefully the user guide has fixed this, if not it's not a user guide issue.

**Closed by richardjgowers** 2020-06-06 12:52 UTC
Labels: Component-Core, Component-Docs
