### ISSUE TITLE
Unable to install in Linux mint 19.1

### ISSUE THREAD

**Issue by debanjansen48** [MDAnalysis/mdanalysis#2730] opened 2020-06-10 12:49 UTC
python2.7 and python 3 is installed
Numpy, scipy,pandas also installed

but still unable to install MDAnalysis

tried to install it using pip ... returns failed to build wheel for MDanalysis
after downloading source code return following errors
plz help

```
Best match: joblib 0.15.1
Processing joblib-0.15.1.tar.gz
Writing /tmp/easy_install-RCJ_Db/joblib-0.15.1/setup.cfg
Running joblib-0.15.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-RCJ_Db/joblib-0.15.1/egg-dist-tmp-qvx0Vd
Traceback (most recent call last):
  File "setup.py", line 622, in <module>
    zip_safe=False,  # as a zipped egg the *.so files are not found (at
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 437, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 679, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 726, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 771, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 774, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1057, in best_match
    return self.obtain(req, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1069, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 724, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 909, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1177, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1163, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-RCJ_Db/joblib-0.15.1/setup.py", line 6, in <module>
    # Copyright (c) 2006-2017 The MDAnalysis Development Team and contributors
  File "/tmp/easy_install-RCJ_Db/joblib-0.15.1/joblib/__init__.py", line 113, in <module>
  File "/tmp/easy_install-RCJ_Db/joblib-0.15.1/joblib/memory.py", line 274
    raise new_exc from exc
                     ^
SyntaxError: invalid syntax
```
## Code to reproduce the behavior ##

``` python
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD,  GRO, PDB, TPR, XTC, TRR,  PRMncdf, NCDF

u = mda.Universe(PSF, DCD)

....

```

## Current version of MDAnalysis ##

- Which version are you using? (run `python -c "import MDAnalysis as mda; print(mda.__version__)"`)
- Which version of Python (`python -V`)?
- Which operating system?

******************
info
```
$ whereis python
python: /usr/bin/python3.6 /usr/bin/python3.6m /usr/bin/python /usr/bin/python3.6m-config /usr/bin/python3.6-config /usr/bin/python2.7-config /usr/bin/python2.7 /usr/lib/python3.6 /usr/lib/python3.8 /usr/lib/python3.7 /usr/lib/python2.7 /etc/python3.6 /etc/python /etc/python2.7 /usr/local/lib/python3.6 /usr/local/lib/python2.7 /usr/include/python3.6 /usr/include/python3.6m /usr/include/python2.7 /usr/share/python /usr/share/man/man1/python.1.gz

$ whereis numpy
numpy: /usr/include/numpy /usr/share/numpy
```

EDIT (@orbeckst): joined error outputs and formatted as preformatted.

**Comment by orbeckst** [comment] 2020-06-17 22:52
@debanjansen48 do you have any more feedback? Otherwise we'll assume that the fixes in #2736 solve the problem and close this issue.

**Comment by debanjansen48** [comment] 2020-06-18 17:21
As per your recommendation I did not try that with conda. as i am facing
some issues regarding the installation of Anaconda in linuxMint.
Once I am able to install anaconda/conda in my system I will try to install
MDAnalysis.

**Comment by orbeckst** [comment] 2020-10-24 00:44
If this issue is not resolved please let us know and we will reopen.

**Closed by orbeckst** 2020-10-24 00:44 UTC
Labels: Python-2, installation, more information needed

**Comment by debanjansen48** [comment] 2020-10-26 13:15
Due to my illness I was unable to reply. sorry for the late reply. Thank you

**Comment by orbeckst** [comment] 2020-10-26 15:57
@debanjansen48 I'm  sorry to hear that you were not well. I hope you're feeling and getting better.

We can re-open the issue – it's not a problem. We normally close issues after a while if there had been no activity and we can't reproduce the bug locally. That doesn't mean that the problem doesn't exist, just that there's insufficient information for us to do anything. When we get more information/feedback we will revisit and reopen. Just let us know.

**Comment by debanjansen48** [comment] 2020-10-27 11:26
Using conda I am able to install it. It works

Thanks sir.

**Comment by orbeckst** [comment] 2020-10-27 16:26
Thanks for the feedback – glad that it worked out! If you have questions, ask on the mailing list https://groups.google.com/group/mdnalysis-discussion
