### ISSUE TITLE
cannot pickle universe object

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MDAnalysis/mdanalysis#173] opened 2015-04-04 00:43 UTC
```
What steps will reproduce the problem?
1. Create a universe object by passing a psf file and a dcd file
          u = universe(psf, dcd)
2. Try to serialize this object by using python pickle module
          u_blob = pickle.dumps(u)

What is the expected output? What do you see instead?
Expected output should be a byte stream, but I got error message 'TypeError: 
'AtomGroup' object is not callable'

What version of the product are you using? On what operating system?

MDAnalysis 0.8.0
Python 2.7.6 / Python 2.6.2
Arch Linux / CentOS

Please provide any additional information below.


```

Original issue reported on code.google.com by `charlesz...@gmail.com` on 27 Mar 2014 at 9:18

**Comment by orbeckst** [comment] 2016-04-29 23:35
Is this going to be solved by #643 ?

**Comment by richardjgowers** [comment] 2016-04-30 13:50
Sort of, Universe pickle will just call topology.pickle and
trajectory.pickle. 643 is most of the hard work though

**Comment by dotsdl** [comment] 2016-05-06 09:17
As currently written ``Topology`` can be pickled, but the 10M atom system I've been playing with takes much longer to deserialize from disk and the filesize of the pickle is nearly 7 times larger than the JSON. I think if we decide to stick with JSON as the preferred serialization for topologies, we can just define the JSONified topology as the output of ``__setstate__`` (and likewise de-JSONifying for ``__getstate__``).

Trajectory pickling is probably just going to have to be pickling/unpickling the filepaths. Will be sufficient for multiprocessing or distributed computing on a common filesystem.

**Comment by kain88-de** [comment] 2016-05-06 09:37
@dotsdl did you enable compression for the pickle? The standard pickle protocol is super inefficient. If you change it the results are comparable to JSON. I had the same problems deciding how to store offsets in the xdrlib refactor.

**Comment by dotsdl** [comment] 2016-05-06 09:39
@kain88-de I didn't; I'll give that a try and report back. I suppose if there's no benefit to JSONifying the topology before pickling we can skip that step entirely? Or is there still value in only serializing what we know we need to regenerate the `Topology` object completely?

**Comment by richardjgowers** [comment] 2017-01-12 12:35
This is a duplicate of #878 as that revolves around unpickling a Universe

**Closed by richardjgowers** 2017-01-12 12:35 UTC
Labels: auto-migrated, Component-Topology, enhancement, persistence, Priority-Medium
