### ISSUE TITLE
MDAnalysis from conda-forge not support Gromacs 2023 (tpx version 129)

### ISSUE THREAD

**Issue by supernova4869** [MDAnalysis/mdanalysis#4341] opened 2023-11-10 07:43 UTC
MDAnalysis from conda-forge does not support Gromacs 2023 (tpx version 129).
As a result, I need to re-generate a tpr file by lower version of gromacs. 
According to #4047, GROMACS 2023 TPR is supported since MDAnalysis 2.5.0. But I installed MDAnalysis by conda from conda-forge (as the documentation `conda install mdanalysis -c conda-forge`). The version is 2.6.1 as following code:
```python
>>> import MDAnalysis
/opt/anaconda3/lib/python3.11/site-packages/MDAnalysis/topology/TPRParser.py:161: DeprecationWarning: 'xdrlib' is deprecated and slated for removal in Python 3.13
  import xdrlib
>>> MDAnalysis.__version__
'2.6.1'
```

_Originally posted by @supernovaZhangJiaXing in https://github.com/MDAnalysis/mdanalysis/issues/4320#issuecomment-1802322649_

**Comment by IAlibay** [comment] 2023-11-10 07:49
@supernovaZhangJiaXing could you provide the code you use for loading this TPR & error message you get?

**Comment by supernova4869** [comment] 2023-11-12 18:05
> @supernovaZhangJiaXing could you provide the code you use for loading this TPR & error message you get?

Sure. I tried the files in [md129.zip](https://github.com/MDAnalysis/mdanalysis/files/13328741/md129.zip), by running the following command:
```python
import MDAnalysis as mda
mda.Universe("md.tpr", "md_dt20ns.xtc")
```
And raised error as:
```
Traceback (most recent call last):
  File "D:\Programs\anaconda3\lib\site-packages\MDAnalysis\core\universe.py", line 110, in _topology_from_file_like
    topology = p.parse(**kwargs)
  File "D:\Programs\anaconda3\lib\site-packages\MDAnalysis\topology\TPRParser.py", line 206, in parse
    th = tpr_utils.read_tpxheader(data)                    # tpxheader
  File "D:\Programs\anaconda3\lib\site-packages\MDAnalysis\topology\tpr\utils.py", line 232, in read_tpxheader
    fileVersion_err(fileVersion)
  File "D:\Programs\anaconda3\lib\site-packages\MDAnalysis\topology\tpr\utils.py", line 207, in fileVersion_err
    raise NotImplementedError(
NotImplementedError: Your tpx version is 129, which this parser does not support, yet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Programs\anaconda3\lib\site-packages\MDAnalysis\core\universe.py", line 346, in __init__
    topology = _topology_from_file_like(self.filename,
  File "D:\Programs\anaconda3\lib\site-packages\MDAnalysis\core\universe.py", line 125, in _topology_from_file_like
    raise ValueError(
ValueError: Failed to construct topology from file md.tpr with parser <class 'MDAnalysis.topology.TPRParser.TPRParser'>.
Error: Your tpx version is 129, which this parser does not support, yet
```
Both windows and Rocky 9 raised this error.

**Comment by IAlibay** [comment] 2023-11-12 18:27
@supernovaZhangJiaXing unfortunately I can't reproduce this locally at all on a fresh 2.6.1 installation on linux.

Can you re-run that script but calling `print(mda.__version__)` on the second line? I'd be keen to seen if maybe it's the interpreter getting a bit confused.

**Comment by IAlibay** [comment] 2023-12-23 22:58
@supernovaZhangJiaXing given the lack of further updates here, and the fact that this cannot be reproduced on our end, I will be closing this issue. Please do re-open it should it remain a problem for you.

**Closed as completed by IAlibay** 2023-12-23 22:58 UTC
Labels: Format-Gromacs, Component-Topology, more information needed
