### ISSUE TITLE
regression tests fail with numpy-1.11.0b3 due to clash with python-tempdir

### ISSUE THREAD

**Issue by rathann** [MDAnalysis/mdanalysis#765] opened 2016-03-11 23:34 UTC
### Expected behaviour
Regression tests pass.

### Actual behaviour
```
======================================================================
ERROR: test_broken_molecule (MDAnalysisTests.coordinates.test_mol2.TestMol2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-MDAnalysis-0.14.0-1.fc25.x86_64/usr/lib/python2.7/site-packages/MDAnalysisTests/coordinates/test_mol2.py", line 29, in setUp
    self.tmpdir = tempdir.TempDir()
AttributeError: 'function' object has no attribute 'TempDir'
```

### Code to reproduce the behaviour

```
./mda_nosetests -v
```

### Currently version of MDAnalysis:
0.14.0

### Additional info
```
$ rpm -q python2-tempdir python2-numpy
python2-tempdir-0.7.1-1.fc25.noarch
python2-numpy-1.11.0-2.b3.fc25.x86_64
```
It looks like numpy is now providing its own `tempdir` object in `numpy.testing.utils` (https://github.com/numpy/numpy/blob/master/numpy/testing/utils.py#L1845).

**Comment by richardjgowers** [comment] 2016-03-11 23:57
This looks like it's an 'import *' finally biting us. We should remove them
all.

**Comment by jbarnoud** [comment] 2016-03-12 22:04
For the record, I could also reproduce the issue with numpy-1.11.0rc1.

**Comment by jbarnoud** [comment] 2016-03-13 08:33
Fixed by #769 .

**Closed by jbarnoud** 2016-03-13 08:33 UTC
Labels: maintainability, testing

**Comment by orbeckst** [comment] 2016-03-13 23:14
@jbarnoud did you explicitly test with the latest NumPy? Does it properly import now?

We can't write a proper test for this but it would be good to have one explicit manual and recorded test.

**Comment by jbarnoud** [comment] 2016-03-13 23:21
I tested both 1.11.0b3 and 1.11.0rc1. 
Le 14 mars 2016 00:14, Oliver Beckstein <notifications@github.com> a écrit :@jbarnoud did you explicitly test with the latest NumPy? Does it properly import now?

We can't write a proper test for this but it would be good to have one explicit manual and recorded test.

**Comment by orbeckst** [comment] 2016-03-14 00:22
Great, thanks!

--
Oliver Beckstein
email: orbeckst@gmail.com


Am Mar 13, 2016 um 16:21 schrieb Jonathan Barnoud <notifications@github.com>:

> I tested both 1.11.0b3 and 1.11.0rc1

**Comment by rathann** [comment] 2016-03-14 12:40
Works for me as well, thanks!
