### ISSUE TITLE
Restructure documentation for user-friendliness

### ISSUE THREAD

**Issue by dotsdl** [MDAnalysis/mdanalysis#1175] opened 2017-01-18 19:06 UTC
The [MDAnalysis documentation](http://pythonhosted.org/MDAnalysis/) is structured in such a way that it contains scant information on the [user interface](http://pythonhosted.org/MDAnalysis/documentation_pages/overview.html) and otherwise gives detail on the internal components of MDAnalysis that users should never really have to touch directly ([parsers](http://pythonhosted.org/MDAnalysis/documentation_pages/topology_modules.html), [readers and writers](http://pythonhosted.org/MDAnalysis/documentation_pages/coordinates_modules.html)). We've seen usage on the mailing list from users in which they try e.g. to directly use a `Reader` object to parse a trajectory, and the docs don't make it clear that this isn't really the way to go about things.

I think the docs should be restructured to have three parts. The first part should read more like the [MDAnalysis Tutorial](http://www.mdanalysis.org/MDAnalysisTutorial/), giving a friendly view as to *how* one uses `MDAnalysis` in practice. The second part should be an API reference, with the full sphinx autodoc output for the user interface components showed in part one. The last part should be the developer docs, which would include the reference docs for internal components, such as parsers, readers, and writers so that they are *somewhere*.

Thoughts?

**Comment by richardjgowers** [comment] 2017-01-19 10:19
I liked the idea of a tiered approach, first there should be an explanation of *how* it works, and only after an explanation of *why*.

**Comment by richardjgowers** [comment] 2017-01-23 10:15
So thinking about this, the only problem is that there is potential for the `rst` and `py` docs to diverge.

So one option would be to later implement doc testing on our first part/tutorial so that it always works as intended

http://doc.pytest.org/en/latest/doctest.html

**Comment by kain88-de** [comment] 2017-01-25 12:04
Related I just found out that scikit-learn has a Circle-CI setup that uploads the changes for a document  build. This allows a reviewer to quickly check the result and give comments without building it himself.

https://8425-843222-gh.circle-artifacts.com/0/home/ubuntu/scikit-learn/doc/_build/html/stable/_changed.html

**Comment by orbeckst** [comment] 2017-02-18 16:53
From the scikit-learn example that @kain88-de linked I found out about http://sphinx-gallery.readthedocs.io , which allows one to make nice docs from small scripts. Maybe worthwhile looking into in conjunction with the proposed examples gallery MDAnalysis/MDAnalysis.github.io#4 .

**Comment by orbeckst** [comment] 2017-05-01 21:44
Although this could go into a patch level, I am retargeting to 0.17.0 so that we can focus on fixing bugs for 0.16.1.

**Comment by orbeckst** [comment] 2017-05-26 08:59
Should perhaps also include #360 
* update formats tables with the appropriate keyword value for `format` or `topology_format`
* user docs on "how to read different file formats into MDAnalysis" 

Also see discussion there regarding user/developer docs.

**Comment by orbeckst** [comment] 2017-08-30 18:33
More for the wish list: *system building*
* creating new segments (see also #1105 and @richardjgowers how-to https://github.com/MDAnalysis/mdanalysis/issues/1268#issuecomment-291436447 )
* adding atoms/residues
* deleting parts of a system
* merging AtomGroups and creating a new Universe (even with trajectory: see [MemoryReader docs](http://www.mdanalysis.org/docs/documentation_pages/coordinates/memory.html#creating-an-in-memory-trajectory-of-a-sub-system))

**Comment by orbeckst** [comment] 2017-09-29 22:00
More from other issues with the Component-Docs tag: All along the lines of *How to add new properties to an AtomGroup*
- adding bfactors = temperaturefactors #1359
- adding occupancies #1092 
- adding charges (to build PQR files)

Although this is advanced stuff, we could start putting it into the currently very, very thin section [The topology system](https://www.mdanalysis.org/mdanalysis/documentation_pages/topology.html), at least for a start.

**Comment by orbeckst** [comment] 2017-10-25 06:33
A while back @tylerjereddy suggested to do separate pages for classes. Apparently, something like this can be automated with sphinx's [autosummary](http://www.sphinx-doc.org/en/stable/ext/autosummary.html#directive-autosummary) directive.

**Comment by orbeckst** [comment] 2017-12-09 15:38
Doc rewrite is not going to happen for 0.17.0 – I am moving it down.

**Comment by orbeckst** [comment] 2017-12-09 16:18
More docs todo on loading trajectories:
- describe Universe properly (include the **trajectory** argument in the docs!!), and all the ways in which trajectories can be loaded (ChainReader can take lists, lists of tuple (name, format))
- clarify memory reader (see https://github.com/MDAnalysis/mdanalysis/issues/1453#issuecomment-323649266 )

**Comment by orbeckst** [comment] 2018-03-12 22:28
Update docs on **selections**
* *groupselections*: syntax, example, see https://groups.google.com/d/msg/mdnalysis-discussion/ZEuJ5wPPLs4/mDlZyqN9BwAJ
* update examples
* geometric selections (especially with PBC)

**Comment by orbeckst** [comment] 2018-07-11 07:56
https://github.com/astropy/sphinx-automodapi looks interesting (see the [automodapi docs](http://sphinx-automodapi.readthedocs.io/en/latest/)): it can automatically create the complete API docs for a whole package. Might be useful once we really split the docs in
* introductory
* API
* developer docs

There's also the [sphinx.ext.autosummary](http://www.sphinx-doc.org/en/stable/ext/autosummary.html) extension.

**Comment by orbeckst** [comment] 2018-11-28 23:15
Docs on extending topologies (thanks to #363)
* adding "known" attributes such as "bfactors", see [MDAnalysisTutorial: Coloring by B-factor](https://www.mdanalysis.org/MDAnalysisTutorial/writing.html#example-saving-dynamic-per-atom-properties-in-b-factor) or [Workshop 2018: introduction_MDAnalysis.ipynb: Visualization](https://render.githubusercontent.com/view/ipynb?commit=d6baedf8454afe20f04ac47a706d53270229980e&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f4d44416e616c797369732f576f726b73686f704861636b6174686f6e323031382f643662616564663834353461666532306630346163343761373036643533323730323239393830652f30315f496e74726f546f4d44416e616c797369732f6e6f7465626f6f6b732f696e74726f64756374696f6e5f4d44416e616c797369732e6970796e62&nwo=MDAnalysis%2FWorkshopHackathon2018&path=01_IntroToMDAnalysis%2Fnotebooks%2Fintroduction_MDAnalysis.ipynb&repository_id=145646867&repository_type=Repository#Visualization) where we add all attributes that would be present in a PDB file.
* adding custom attributes https://gist.github.com/richardjgowers/85a652e61690143b04d35acbac1fa2b5
* adding custom methods https://gist.github.com/richardjgowers/85a652e61690143b04d35acbac1fa2b5

**Comment by orbeckst** [comment] 2019-03-13 20:58
Google launched [Season of Docs](https://developers.google.com/season-of-docs/) – this issue looks like a suitable starting point for a tech writer who would want to work with MDAnalysis.

**Comment by orbeckst** [comment] 2019-10-22 17:31
@lilyminium with your GSoD project, this is your area :-)

**Comment by richardjgowers** [comment] 2020-03-06 09:59
I'm gonna say @lilyminium has done this

**Closed by richardjgowers** 2020-03-06 09:59 UTC
Labels: Component-Docs
